10 REM C64 BASIC CONTROL CODES DEMO
20 PRINT CHR$(147): PRINT : PRINT : PRINT
30 PRINT "{WHITE}CONTROL CODES DEMO{LIGHTBLUE}"
40 PRINT "{13}-------------------"
50 PRINT
60 PRINT 
70 PRINT "{HOME}";"HOME","SCREEN CONTROLS:"
80 PRINT "{DOWN}";"DOWN";"  {UP}";"UP      ";:PRINT
90 PRINT "{LEFT}";" LEFT";"  {RIGHT}";"RIGHT";:PRINT
100 PRINT "{DEL}";" DEL   {INS}";"INS";:PRINT
110 PRINT
120 PRINT "REVERSE VIDEO: {RVS}ON{RVS OFF} AND {RVS}OFF{RVS OFF}"
130 PRINT
140 PRINT "COLORS:" : PRINT
150 PRINT " {BLACK}";"BLACK  ";"{WHITE}";"WHITE  ";"{RED}";"RED  ";"{CYAN}";"CYAN"
160 PRINT " {PURPLE}";"PURPLE ";"{GREEN}";"GREEN ";"{BLUE}";"BLUE  ";"{YELLOW}";"YELLOW"
170 PRINT " {ORANGE}";"ORANGE ";"{BROWN}";"BROWN ";"{PINK}";"PINK  ";"{GRAY1}";"GRAY1"
180 PRINT " {GRAY2}";"GRAY2 ";"{GRAY3}";"GRAY3 ";"{LIGHTGREEN}";"LIGHTGREEN"
190 PRINT " {LIGHTBLUE}";"LIGHTBLUE"
200 PRINT
210 PRINT "MIXED TEXT: ";"{YELLOW}";"YELLOW ";"{GREEN}";"GREEN ";"{BLUE}";"BLUE";"{WHITE}"
220 PRINT
230 PRINT
240 PRINT "PRESS ANY KEY...";
245 GET A$:IF A$="" THEN GOTO 245
250 PRINT "{CLR}";"DONE"
260 END
