REM Simple smoke test for CURSOR and COLOR
PRINT "CURSOR/COLOR/BACKGROUND TEST"
CURSOR OFF
COLOR 2
PRINT "THIS SHOULD BE RED"
COLOR 1
PRINT "BACK TO WHITE"
BACKGROUND 2
PRINT "RED BACKGROUND"
BACKGROUND 0
CURSOR ON
END

