1 REM Test ENV$ and PLATFORM$
2 PRINT "Testing ENV$..."
3 X$ = ENV$("PATH")
4 IF LEN(X$) > 0 THEN PRINT "OK: ENV$ PATH"
5 Y$ = ENV$("NONEXISTENT_VAR_12345")
6 IF LEN(Y$) = 0 THEN PRINT "OK: ENV$ missing"
7 PRINT "Testing PLATFORM$..."
8 PL$ = PLATFORM$()
9 IF LEN(PL$) > 0 THEN PRINT "OK: PLATFORM$"; PL$
10 PRINT "ENV$/PLATFORM$ test done."
