REM Test INDEXOF and LASTINDEXOF
PRINT "Testing INDEXOF/LASTINDEXOF..."
DIM A(2)
A(0) = 10 : A(1) = 20 : A(2) = 10
IF INDEXOF(A, 10) = 1 THEN PRINT "OK: INDEXOF first"
IF LASTINDEXOF(A, 10) = 3 THEN PRINT "OK: LASTINDEXOF"
IF INDEXOF(A, 20) = 2 THEN PRINT "OK: INDEXOF middle"
IF INDEXOF(A, 99) = 0 THEN PRINT "OK: INDEXOF not found"
DIM B$(2)
B$(0) = "x" : B$(1) = "y" : B$(2) = "x"
IF INDEXOF(B$, "x") = 1 THEN PRINT "OK: INDEXOF string"
IF LASTINDEXOF(B$, "x") = 3 THEN PRINT "OK: LASTINDEXOF string"
IF INDEXOF(B$, "z") = 0 THEN PRINT "OK: INDEXOF string not found"
PRINT "INDEXOF/LASTINDEXOF test done."
