1 REM Phase 1 JSON helpers: JSONESC$, JSONNUM, JSONBOOL, JSONTYPE$
2 REM RGC-BASIC interprets \n \t \r \" \\ inside string literals; double the
2 REM backslash whenever a literal '\' is needed in an expected-output string.
3 Q$ = CHR$(34)
4 PRINT "Testing JSONESC$..."
10 IF JSONESC$("hello") = "hello" THEN PRINT "OK: passthrough"
11 IF JSONESC$("he said " + Q$ + "hi" + Q$) = "he said \\" + Q$ + "hi\\" + Q$ THEN PRINT "OK: quote escape"
12 IF JSONESC$("a\\b") = "a\\\\b" THEN PRINT "OK: backslash escape"
13 IF JSONESC$("line1" + CHR$(10) + "line2") = "line1\\nline2" THEN PRINT "OK: newline"
14 IF JSONESC$(CHR$(9)) = "\\t" THEN PRINT "OK: tab"
15 IF JSONESC$(CHR$(13)) = "\\r" THEN PRINT "OK: cr"
16 IF JSONESC$(CHR$(8)) = "\\b" THEN PRINT "OK: backspace"
17 IF JSONESC$(CHR$(12)) = "\\f" THEN PRINT "OK: formfeed"
18 IF JSONESC$(CHR$(1)) = "\\u0001" THEN PRINT "OK: control char 0x01"
19 IF JSONESC$(CHR$(31)) = "\\u001f" THEN PRINT "OK: control char 0x1f"
20 IF JSONESC$("") = "" THEN PRINT "OK: empty"
21 IF JSONESC$("a/b") = "a/b" THEN PRINT "OK: forward slash unchanged"
30 PRINT "Testing JSONNUM..."
40 J$ = "{" + Q$ + "n" + Q$ + ":42," + Q$ + "f" + Q$ + ":3.14," + Q$ + "s" + Q$ + ":" + Q$ + "no" + Q$ + "," + Q$ + "neg" + Q$ + ":-7," + Q$ + "big" + Q$ + ":12345678}"
41 IF JSONNUM(J$, "n") = 42 THEN PRINT "OK: integer"
42 IF JSONNUM(J$, "f") > 3.13 AND JSONNUM(J$, "f") < 3.15 THEN PRINT "OK: decimal"
43 IF JSONNUM(J$, "s") = 0 THEN PRINT "OK: non-numeric returns 0"
44 IF JSONNUM(J$, "missing") = 0 THEN PRINT "OK: missing returns 0"
45 IF JSONNUM(J$, "neg") = -7 THEN PRINT "OK: negative"
46 IF JSONNUM(J$, "big") = 12345678 THEN PRINT "OK: large int parsed exactly"
50 PRINT "Testing JSONBOOL..."
60 J2$ = "{" + Q$ + "t" + Q$ + ":true," + Q$ + "f" + Q$ + ":false," + Q$ + "n" + Q$ + ":1," + Q$ + "s" + Q$ + ":" + Q$ + "true" + Q$ + "}"
61 IF JSONBOOL(J2$, "t") = 1 THEN PRINT "OK: true"
62 IF JSONBOOL(J2$, "f") = 0 THEN PRINT "OK: false"
63 IF JSONBOOL(J2$, "n") = 0 THEN PRINT "OK: number is not bool"
64 IF JSONBOOL(J2$, "s") = 0 THEN PRINT "OK: string 'true' is not bool"
65 IF JSONBOOL(J2$, "missing") = 0 THEN PRINT "OK: missing returns 0"
70 PRINT "Testing JSONTYPE$..."
80 J3$ = "{" + Q$ + "s" + Q$ + ":" + Q$ + "x" + Q$ + "," + Q$ + "n" + Q$ + ":1," + Q$ + "f" + Q$ + ":1.5," + Q$ + "neg" + Q$ + ":-9," + Q$ + "b" + Q$ + ":true," + Q$ + "z" + Q$ + ":false," + Q$ + "u" + Q$ + ":null," + Q$ + "o" + Q$ + ":{}," + Q$ + "a" + Q$ + ":[]}"
81 IF JSONTYPE$(J3$, "s") = "string" THEN PRINT "OK: type string"
82 IF JSONTYPE$(J3$, "n") = "number" THEN PRINT "OK: type number int"
83 IF JSONTYPE$(J3$, "f") = "number" THEN PRINT "OK: type number float"
84 IF JSONTYPE$(J3$, "neg") = "number" THEN PRINT "OK: type number negative"
85 IF JSONTYPE$(J3$, "b") = "bool" THEN PRINT "OK: type bool true"
86 IF JSONTYPE$(J3$, "z") = "bool" THEN PRINT "OK: type bool false"
87 IF JSONTYPE$(J3$, "u") = "null" THEN PRINT "OK: type null"
88 IF JSONTYPE$(J3$, "o") = "object" THEN PRINT "OK: type object"
89 IF JSONTYPE$(J3$, "a") = "array" THEN PRINT "OK: type array"
90 IF JSONTYPE$(J3$, "missing") = "" THEN PRINT "OK: type missing returns empty"
99 PRINT "Phase 1 test done."
