REM NOT unary logical negation
IF NOT FALSE THEN PRINT "NOT FALSE ok"
IF NOT TRUE THEN PRINT "FAIL NOT TRUE"
IF NOT 0 THEN PRINT "NOT 0 ok"
IF NOT 1 THEN PRINT "FAIL NOT 1"
IF NOT (1=2) THEN PRINT "NOT (1=2) ok"
X = 5
IF NOT X = 3 THEN PRINT "NOT X=3 ok"
IF NOT NOT TRUE THEN PRINT "NOT NOT TRUE ok"
PRINT "OK"
