REM SCREEN 1 + SPRITE LOAD + SPRITE DRAW — portable surface.
SCREEN 1
BACKGROUND 6
CLS
SPRITE LOAD 0, "ship.png"
X = 0
DO
  IF KEYDOWN(81) THEN EXIT
  SPRITE DRAW 0, X, 100
  X = X + 1
  IF X > 320 THEN X = 0
  VSYNC
LOOP
END
