PRINT CHR$(147)
PRINT "CLR/HOME DONE"
PRINT "BASE COLORS:"
PRINT CHR$(5);"  ";CHR$(144);"BLACK";CHR$(5)
PRINT "  ";  CHR$(5);"WHITE";CHR$(5)
PRINT "    " ;CHR$(28);"RED";CHR$(5)
PRINT "   ";CHR$(159);"CYAN";CHR$(5)
PRINT " ";CHR$(156);"PURPLE";CHR$(5)
PRINT "  "; CHR$(30);"GREEN";CHR$(5)
PRINT "   "; CHR$(31);"BLUE";CHR$(5)
PRINT " ";CHR$(158);"YELLOW";CHR$(5)
PRINT
PRINT "EXTENDED COLORS:"
PRINT CHR$(129);"ORANGE     ";CHR$(5)
PRINT CHR$(149);"BROWN      ";CHR$(5)   
PRINT CHR$(150);"LIGHT RED  ";CHR$(5)
PRINT CHR$(151);"DARK GRAY  ";CHR$(5)
PRINT CHR$(152);"MEDIUM GRAY";CHR$(5)
PRINT CHR$(153);"LIGHT GREEN";CHR$(5)
PRINT CHR$(154);"LIGHT BLUE ";CHR$(5)
PRINT CHR$(155);"LIGHT GRAY ";CHR$(5)
END
