#OPTION PETSCII
SCREENCODES ON : BACKGROUND 0
REM ** SUPER STAR TREK -- STRUCTURED (STATE-MACHINE) VERSION
REM ** BY MIKE MAYFIELD 1974
REM ** MODIFIED BY DAVID AHL 1978
REM ** CONVERTED TO 40 COLUMNS
REM ** BY ELECTRON.GREG 2022-2023
REM ** MODIFIED BY CHRIS GARRETT 2025
REM ** ( FOR TUTORIAL USE )
REM ** SUPPORT ELECTRON.GREG
REM ** https://electrongreg.itch.io/
REM **
REM ** THE WHOLE GAME IS DRIVEN BY ONE STATE LOOP (BELOW). EACH STATE
REM ** IS A FUNCTION THAT DOES ITS WORK AND RETURNS THE NEXT STATE, SO
REM ** THERE ARE NO GOTOS BETWEEN ROUTINES -- ONLY INSIDE THEM.


ST_QUIT=0 : ST_NEWGAME=1 : ST_NEWQUAD=2 : ST_COMMAND=3 : ST_DEAD=4
ST_GAMEOVER=5 : ST_VICTORY=6 : ST_MISSIONEND=7 : ST_PLAYAGAIN=8
ES$="E  " : KS$="K  " : BS$="B  " : SS$="*  " : EM$="   "
A1$="NAVSRSLRSPHATORSHEDAMCOMXXXHLP"
InitColours()
DIM G(8,8),C(9,2),K(3,3),N(3),Z(8,8),D(8)
DEF FND(D)=SQR((K(I,1)-S1)^2+(K(I,2)-S2)^2)
DEF FNR(R)=INT(RND(R)*7.98+1.01)


REM ** ===== MAIN STATE LOOP ===== **
REM ** EACH STATE FUNCTION DOES ITS WORK AND RETURNS THE NEXT STATE. WE
REM ** DISPATCH WITH A SELECT CASE AND REPEAT UNTIL A FUNCTION HANDS BACK
REM ** ST_QUIT. NO GOTOS HERE AT ALL -- JUST A DO/LOOP + SELECT CASE. **
GameState = ST_NEWGAME
DO
  SELECT CASE GameState
    CASE ST_NEWGAME
      GameState = SetupGame()
    CASE ST_NEWQUAD
      GameState = EnterQuadrant()
    CASE ST_COMMAND
      GameState = DoCommand()
    CASE ST_DEAD
      GameState = ShipDestroyed()
    CASE ST_GAMEOVER
      GameState = ShowGameOver()
    CASE ST_VICTORY
      GameState = ShowVictory()
    CASE ST_MISSIONEND
      GameState = ShowMissionEnd()
    CASE ST_PLAYAGAIN
      GameState = AskPlayAgain()
  END SELECT
LOOP UNTIL GameState = ST_QUIT
END



REM ** ===== ONE-TIME GAME SETUP (NEW GAME / RESTART) ===== **
FUNCTION SetupGame()
    Z2$="" : ATAKFLAG=0 : SLSFLAG=0 : N=RND(-1)
    PRINT CHR$(147);
    PRINT HCOL$;"{YELLOW}   --S-U-P-E-R---S-T-A-R---T-R-E-K--"
    PRINT "{WHITE}"
    FOR N=1 TO 5 : PRINT : NEXT : PRINT BCOL$;
    PRINT "                    ,------*-------,"
    PRINT "    ,-------------,  '---  -------'"
    PRINT "    '--------{109}{109}--'      / /"
    PRINT "          ,---{109}{109}-------/ /--,"
    PRINT "          '----------------'" : PRINT DCOL$
    PRINT "    THE USS ENTERPRISE --- NCC-1701"
    FOR N=1 TO 5 : PRINT FCOL$ : NEXT : CRSTART=1 : Pause()
    X9=RND(-TI) : REM ** RANDOM SEED GENERATOR **
    PRINT : PRINT "{CLR}           GENERATING GALAXY";
    Z$="                         "
    T=INT(RND(1)*20+20)*100 : T0=T : T9=25+INT(RND(1)*10) : D0=0 : E=3000 : E0=E
    P=10 : P0=P : S9=200 : S=0 : B9=2 : K9=0 : X$="" : X0$=" IS "
    REM INITIALIZE ENTERPRISES POSITION
    Q1=FNR(1) : Q2=FNR(1) : S1=FNR(1) : S2=FNR(1)
    FORI=1TO9 : C(I,1)=0 : C(I,2)=0 : NEXTI
    C(3,1)=-1 : C(2,1)=-1 : C(4,1)=-1 : C(4,2)=-1 : C(5,2)=-1 : C(6,2)=-1
    C(1,2)=1 : C(2,2)=1 : C(6,1)=1 : C(7,1)=1 : C(8,1)=1 : C(8,2)=1 : C(9,2)=1
    FORI=1TO8 : D(I)=0 : NEXTI
    REM SETUP WHAT EXISTS IN GALAXY . . .
    REM K3= # KLINGONS  B3= # STARBASES  S3 = # STARS
    FORI=1TO8 : PRINT "."; : FORJ=1TO8 : K3=0 : Z(I,J)=0 : R1=RND(1)
    SELECT CASE R1
    CASE IS > .98
        K3=3 : K9=K9+3
    CASE IS > .95
        K3=2 : K9=K9+2
    CASE IS > .80
        K3=1 : K9=K9+1
    END SELECT
    B3=0 : IFRND(1)>.96THENB3=1 : B9=B9+1
    G(I,J)=K3*100+B3*10+FNR(1) : NEXTJ : NEXTI : IFK9>T9 THEN T9=K9+1
    PRINT
    ShowKey() : REM ** KEY TO SRS ICONS **
    ShowCommands() : REM ** USE THESE COMMANDS LIST **
    PRINT : Pause() : REM ** PAUSE **
    IF B9<>0 THEN GOTO ShowOrders
    IF G(Q1,Q2)<200 THEN G(Q1,Q2)=G(Q1,Q2)+120 : K9=K9+1
    B9=1 : G(Q1,Q2)=G(Q1,Q2)+10 : Q1=FNR(1) : Q2=FNR(1)
    ShowOrders: K7=K9 : IF B9<>1 THEN X$="S" : X0$=" ARE "
    PRINT : PRINT "{CLR}{REVERSE ON}YOUR ORDERS ARE AS FOLLOWS:{REVERSE OFF}" : PRINT
    PRINT "DESTROY THE ";K9;" KLINGON WARSHIPS BEFORE"
    PRINT "STARDATE ";T0+T9;". THIS GIVES YOU ";T9;" DAYS."
    PRINT "THERE";X0$;B9;" STARBASE";X$;" IN THE GALAXY"
    PRINT "FOR RESUPPLYING & REPAIRING YOUR SHIP."
    I=RND(1)
    RETURN ST_NEWQUAD
END FUNCTION




REM ** ===== ENTER A QUADRANT: SET IT UP, PLACE OBJECTS, SHORT SCAN ===== **
FUNCTION EnterQuadrant()
    Z4=Q1 : Z5=Q2 : K3=0 : B3=0 : S3=0 : G5=0 : D4=.5*RND(1) : Z(Q1,Q2)=G(Q1,Q2)
    IF Q1 < 1 OR Q1 >8 OR Q2<1 OR Q2>8 THEN GOTO PlaceObjects
    QuadrantName() : PRINT : IF T0<>T THEN GOTO QuadKnown
    PRINT "YOUR MISSION BEGINS WITH YOUR STARSHIP"
    PRINT "IN THE QUADRANT, ";G2$;"."
    SRSFLAG=1
    PRINT : Pause() : REM ** PAUSE **
    PRINT : GOTO ParseQuadrant
    QuadKnown: IF ATAKFLAG=1 THEN Pause() : ATAKFLAG=0 : PRINT
    SRSFLAG=1 : PRINT "ENTERING ";G2$;" QUADRANT..."
    ParseQuadrant: K3=INT(G(Q1,Q2)*.01) : B3=INT(G(Q1,Q2)*.1)-10*K3
    S3=G(Q1,Q2)-100*K3-10*B3
    FORI=1TO3 : K(I,1)=0 : K(I,2)=0 : NEXTI
    PlaceObjects: FORI=1TO3 : K(I,3)=0 : NEXTI : Q$=Z$+Z$+Z$+Z$+Z$+Z$+Z$+LEFT$(Z$,17)
    REM POSITION ENTERPRISE IN QUADRANT, THEN PLACE "K3" KLINGONS, &
    REM "B3" STARBASES, & "S3" STARS ELSEWHERE.
    A$=ES$ : Z1=S1 : Z2=S2
    PlaceToken()
    IF K3 < 1 THEN GOTO PlaceBase
    FOR I=1 TO K3 : FindEmpty() : A$=KS$ : Z1=R1 : Z2=R2
    PlaceToken() : K(I,1)=R1 : K(I,2)=R2 : K(I,3)=S9*(0.5+RND(1)) : NEXTI
    PlaceBase: IF B3 < 1 THEN GOTO PlaceStars
    FindEmpty() : A$=BS$ : Z1=R1 : B4=R1 : Z2=R2 : B5=R2 : PlaceToken()
    PlaceStars: FOR I=1 TO S3 : FindEmpty() : A$=SS$ : Z1=R1 : Z2=R2 : PlaceToken() : NEXTI
    RETURN ShortRangeScan()
END FUNCTION




REM ** ===== COMMAND PHASE: ENERGY CHECK, PROMPT, DISPATCH ONE COMMAND ===== **
FUNCTION DoCommand()
    MainLoop: IF S+E > 10 THEN IF E>10 OR D(7)=0 THEN GOTO CommandPrompt
    PRINT : PRINT "** FATAL ERROR **"
    PRINT "YOUVE STRANDED YOUR SHIP IN SPACE."
    PRINT "YOU HAVE INSUFFICIENT MANOEUVRING"
    PRINT "ENERGY, & SHIELD CONTROL IS PRESENTLY"
    PRINT "INCAPABLE OF CROSS-CIRCUITING TO"
    PRINT "ENGINE ROOM!!"
    PRINT : Pause()
    RETURN ST_GAMEOVER
    CommandPrompt: PRINT : SRSFLAG=0 : LX=3 : PRINT "{13}{REVERSE ON}{LIGHTBLUE}COMMAND:{REVERSE OFF}{WHITE} "; : GetInput()
    A$=LII$ : Z2$=A$ : ATAKFLAG=0
    IF A$="SLS" THEN SLSFLAG=1
    IF A$="SLS" THEN PRINT : PRINT "{CLR}{REVERSE ON}SHORT & LONG RANGE SCAN...{REVERSE OFF}" : RETURN ShortRangeScan()
    IF A$<>"KEY" THEN GOTO ParseCommand
    ShowKey() : REM KEY TO SRS ICONS
    GOTO CommandPrompt
    ParseCommand: COMFLAG=0 : IF A$="GAL" AND D(8)>=0 THEN A$="COM" : COMFLAG=1
    IF D(8)<0 AND A$="GAL" THEN PRINT : PRINT "SHIPS COMPUTER DISABLED" : GOTO CommandPrompt
    CMD=0 : FOR I=1 TO 10 : IF LEFT$(A$,3)=MID$(A1$,3*I-2,3) THEN CMD=I
    NEXT I
    SELECT CASE CMD
    CASE 1
        RETURN Nav()
    CASE 2
        RETURN ShortRangeScan()
    CASE 3
        RETURN Lrs()
    CASE 4
        RETURN Phasers()
    CASE 5
        RETURN Torpedo()
    CASE 6
        RETURN Shields()
    CASE 7
        RETURN Damage()
    CASE 8
        RETURN Computer()
    CASE 9
        RETURN ST_MISSIONEND
    END SELECT
    ShowCommands()
    GOTO MainLoop
END FUNCTION




REM ** ===== COURSE CONTROL (NAV) ===== **
FUNCTION Nav()
    ShowDirections() : REM ** DIRECTION HELPER **
    PRINT : LX=5 : PRINT "COURSE (1-9) :  "; : GetInput()
    C1=VAL(LII$) : IFC1=9THENC1=1
    IF C1>=1 AND C1<9 THEN GOTO NavWarp
    BACKGROUND 6: COLOR 1
    PRINT : PRINT "LT. SULU REPORTS, INCORRECT COURSE"
    PRINT "DATA, SIR!";: BACKGROUND 0: PRINT
    RETURN ST_COMMAND
    NavWarp: X$="8" : IFD(1)<0THENX$="0.2"
    SRSFLAG=1 : LX=5 : PRINT "WARP FACTOR (0-";X$;") :  "; : GetInput()
    W1=VAL(LII$) : IF D(1)<0 AND W1>.2 THEN GOTO NavWarpDamaged
    IF W1>0 AND W1<=8 THEN GOTO NavEnergyCheck
    IF W1=0 THEN RETURN ST_COMMAND
    PRINT : BACKGROUND 6: COLOR 1:PRINT "CHIEF ENGINEER SCOTT REPORTS THE"
    PRINT "ENGINES WONT TAKE WARP ";W1;"!";: BACKGROUND 0 : RETURN ST_COMMAND
    NavWarpDamaged: PRINT : PRINT "WARP ENGINES ARE DAMAGED."
    PRINT "MAXIMUM SPEED = WARP 0.2" : RETURN ST_COMMAND
    NavEnergyCheck: N=INT(W1*8+.5) : IFE-N>=0THEN GOTO KlingonsMove
    PRINT : BACKGROUND 6: COLOR 1:PRINT "ENGINEERING REPORTS INSUFFICIENT ENERGY";
    PRINT "AVAILABLE FOR WARP ";W1;"!";: BACKGROUND 0
    IF S < N-E OR D(7) < 0 THEN RETURN ST_COMMAND
    PRINT :BACKGROUND 6: COLOR 1: PRINT "DEFLECTOR CONTROL ROOM ACKNOWLEDGES"
    S1$=STR$(S)
    PRINT "SHIELD ENERGY DEPLOYED IS ";S1$;" UNITS.";: BACKGROUND 0
    RETURN ST_COMMAND
    REM KLINGONS MOVE/FIRE ON MOVING STARSHIP . . .
    KlingonsMove: FORI=1 TO K3 : IFK(I,3)=0THEN CONTINUE FOR
    A$=EM$ : Z1=K(I,1) : Z2=K(I,2) : PlaceToken() : FindEmpty()
    K(I,1)=Z1 : K(I,2)=Z2 : A$=KS$ : PlaceToken()
    NEXTI : KlingonsFire()
    IF SHIPDEAD THEN RETURN ST_DEAD
    D1=0 : D6=W1 : IF W1>=1 THEN D6=1
    FORI=1TO8 : IFD(I)>=0THEN CONTINUE FOR
    D(I)=D(I)+D6 : IFD(I)>-.1AND D(I)<0THEND(I)=-.1 : CONTINUE FOR
    IFD(I)<0THEN CONTINUE FOR
    IFD1<>1THEND1=1 : PRINT : PRINT "DAMAGE CONTROL REPORT :   "
    R1=I : DeviceName() : PRINT G2$;" REPAIR COMPLETED"
    NEXTI
    IFRND(1)>.2THEN GOTO MoveShip
    R1=FNR(1) : IFRND(1)>=.6THEN GOTO DamagePartRepair
    D(R1)=D(R1)-(RND(1)*5+1) : PRINT : PRINT "DAMAGE CONTROL REPORTS:"
    DeviceName() : PRINT G2$;" DAMAGED" : GOTO MoveShip
    DamagePartRepair: D(R1)=D(R1)+RND(1)*3+1 : PRINT : PRINT "DAMAGE CONTROL REPORTS:"
    DeviceName() : PRINT G2$;" PARTLY REPAIRED"
    REM BEGIN MOVING STARSHIP
    MoveShip: A$=EM$ : Z1=INT(S1) : Z2=INT(S2) : PlaceToken()
    X1=C(C1,1)+(C(C1+1,1)-C(C1,1))*(C1-INT(C1)) : X=S1 : Y=S2
    X2=C(C1,2)+(C(C1+1,2)-C(C1,2))*(C1-INT(C1)) : Q4=Q1 : Q5=Q2
    FOR I=1 TO N : S1=S1+X1 : S2=S2+X2
        IF S1<1 OR S1>=9 OR S2<1 OR S2>=9THEN GOTO CrossQuadrant
        S8=INT(S1)*24+INT(S2)*3-26 : IFMID$(Q$,S8,2)="  "THEN CONTINUE FOR
        S1=INT(S1-X1) : S2=INT(S2-X2) : PRINT : PRINT "WARP ENGINES SHUT DOWN AT ";
        PRINT "SECTOR ";S1;",";S2
        PRINT "DUE TO BAD NAVIGATION"
        SRSFLAG=1
        GOTO MovePlace
    NEXT I
    S1=INT(S1) : S2=INT(S2)
    MovePlace: A$=ES$ : Z1=INT(S1) : Z2=INT(S2) : PlaceToken() : ManeuverEnergy() : T8=1
    IFW1<1THENT8=.1*INT(10*W1)
    T=T+T8 : IFT>T0+T9THEN RETURN ST_GAMEOVER

    REM SEE IF DOCKED, THEN GET COMMAND
    RETURN ShortRangeScan()
    REM EXCEEDED QUADRANT LIMITS
    CrossQuadrant: X=8*Q1+X+N*X1 : Y=8*Q2+Y+N*X2 : Q1=INT(X/8) : Q2=INT(Y/8) : S1=INT(X-Q1*8)
    S2=INT(Y-Q2*8) : IFS1=0THENQ1=Q1-1 : S1=8
    IFS2=0THENQ2=Q2-1 : S2=8
    X5=0 : IFQ1<1THENX5=1 : Q1=1 : S1=1
    IFQ1>8THENX5=1 : Q1=8 : S1=8
    IFQ2<1THENX5=1 : Q2=1 : S2=1
    IFQ2>8THENX5=1 : Q2=8 : S2=8
    IFX5=0THEN GOTO CrossDone
    PRINT : BACKGROUND 6: COLOR 1: PRINT "LT. UHURA REPORTS MESSAGE FROM STARFLEET";
    PRINT " COMMAND:{13}PERMISSION TO ATTEMPT CROSSING OF GALACTIC PERIMETER IS HEREBY{13}{RED}*DENIED*{WHITE}";
    PRINT " - SHUT DOWN YOUR ENGINES.{13}{13} CHIEF ENGINEER SCOTT REPORTS WARP";
    PRINT " ENGINES SHUT DOWN AT SECTOR ";S1;",";S2;" OF QUADRANT ";Q1;",";Q2;".";:
    BACKGROUND 0: PRINT
    SRSFLAG=1
    PRINT : Pause()
    IFT>T0+T9THEN RETURN ST_GAMEOVER
    CrossDone: IF8*Q1+Q2=8*Q4+Q5THEN GOTO MovePlace
    T=T+1 : ManeuverEnergy() : RETURN ST_NEWQUAD
END FUNCTION




REM MANEUVER ENERGY S/R **
FUNCTION ManeuverEnergy()
    E=E-N-10 : IFE>=0THENRETURN
    PRINT : PRINT "SHIELD CONTROL SUPPLIES ENERGY TO"
    PRINT "COMPLETE THE MANOEUVRE."
    S=S+E : E=0 : IFS<=0THENS=0
    RETURN
END FUNCTION




REM ** ===== LONG RANGE SCAN ===== **
FUNCTION Lrs()
    K1=0
    IFD(3)<0THENPRINT : PRINT "LONG RANGE SENSORS ARE INOPERABLE"
    IFD(3)<0THEN SLSFLAG=0 : RETURN ST_COMMAND
    PRINT : PRINT "{13}{LIGHTBLUE}LONG RANGE SCAN FOR QUADRANT{WHITE} ";Q1;",";Q2
    PRINT : O1$=" ┌─────┬─────┬─────┐" : PRINT "{13}{GREEN}";O1$;
    O2$=" ├─────┼─────┼─────┤":O3$=" {173}─────{177}─────{177}─────{189}" 
    PRINT "         ";ECOL$;"#";DCOL$;"#";HCOL$;"#";FCOL$
    FOR I=Q1-1 TO Q1+1 : N(1)=-1 : N(2)=-2 : N(3)=-3 : FOR J=Q2-1 TO Q2+1
    IF I>0 AND I<9 AND J>0 AND J<9 THEN N(J-Q2+2)=G(I,J) : Z(I,J)=G(I,J)
    NEXTJ : FORL=1TO3
    IF K1=2 AND L=3 THEN PRINT "";
    PRINT " {221}";
    IF K1=2 AND L=2 THEN PRINT " "; : GOTO LrsCell
    PRINT " ";
    LrsCell: IFN(L)<0THEN PRINT "▒▒▒"; : GOTO LrsColDone
    G1$=RIGHT$(STR$(N(L)+1000),3)
    G2$=ECOL$+MID$(G1$,1,1) : PRINT G2$;
    G2$=DCOL$+MID$(G1$,2,1) : PRINT G2$;
    G2$=HCOL$+MID$(G1$,3,1) : PRINT G2$;FCOL$;
    LrsColDone: NEXTL : PRINT " {221}"; : K1=K1+1
    IF K1=1 THEN PRINT "        . . ."
    IF K1=3 THEN PRINT "      .   .   ."
    IF K1=5 THEN PRINT "    .           ."
    K1=K1+1 : IF K1<6 THEN PRINT O2$;
    IF K1=6 THEN PRINT O3$;
    IF K1=2 THEN PRINT "       .  .  ."
    IF K1=4 THEN PRINT "     .  {CYAN}BASES{GREEN}";
    IF K1=4 THEN PRINT "  ."
    IF K1=6 THEN PRINT "  {PINK}KLINGONS{WHITE}    {YELLOW}STARS{WHITE}"
    NEXT I : K1=0 : IF SLSFLAG=1 THEN SLSFLAG=0
    RETURN ST_COMMAND
END FUNCTION


REM ** ===== PHASER CONTROL ===== **
FUNCTION Phasers()
    IF D(4)<0 THEN PRINT : PRINT "PHASERS INOPERATIVE" : RETURN ST_COMMAND
    IF K3>0 THEN GOTO PhasersFire
    NoEnemyMsg() : RETURN ST_COMMAND
    PhasersFire: IFD(8)<0 THEN PRINT : PRINT "COMPUTER FAILURE HAMPERS ACCURACY"
    PRINT : PRINT "PHASERS LOCKED ON TARGET!  "
    PhasersEnergy: PRINT : PRINT "ENERGY AVAILABLE = ";E;" UNITS"
    LX=5 : PRINT "NUMBER OF UNITS TO FIRE :  "; : GetInput()
    X=VAL(LII$) : IF X<=0 THEN RETURN ST_COMMAND
    IF E-X<0 THEN GOTO PhasersEnergy
    E=E-X : IFD(7)<0 THEN X=X*RND(1)
    H1=INT(X/K3) : FOR I=1 TO 3 : IFK(I,3)<=0 THEN CONTINUE FOR
    H=INT((H1/FND(0))*(RND(1)+2)) : IF H>.15*K(I,3) THEN GOTO PhaserHit
    PRINT : PRINT " SENSORS SHOW NO DAMAGE TO ENEMY"
    PRINT " AT ";K(I,1);",";K(I,2)
    CONTINUE FOR
    PhaserHit: K(I,3)=K(I,3)-H : PRINT
    PRINT H;" UNIT HIT KLINGON AT ";K(I,1);",";K(I,2)
    IF K(I,3)<=0 THEN PRINT " *** KLINGON DESTROYED ***" : GOTO KlingonDestroyed
    PRINT " (SENSORS SHOW ";INT(K(I,3));" UNITS REMAINING)"
    CONTINUE FOR
    KlingonDestroyed: K3=K3-1 : K9=K9-1 : Z1=K(I,1) : Z2=K(I,2) : A$=EM$ : PlaceToken()
    K(I,3)=0 : G(Q1,Q2)=G(Q1,Q2)-100 : Z(Q1,Q2)=G(Q1,Q2) : IF K9<=0 THEN RETURN ST_VICTORY
    NEXTI
    IF K3>0 THEN PRINT : Pause()
    KlingonsFire()
    IF SHIPDEAD THEN RETURN ST_DEAD
    RETURN ST_COMMAND
END FUNCTION


REM ** ===== PHOTON TORPEDO ===== **
FUNCTION Torpedo()
    IF P<=0 THEN PRINT : PRINT "ALL PHOTON TORPEDOES EXPENDED" : RETURN ST_COMMAND
    IF D(5)<0 THEN PRINT : PRINT "PHOTON TUBES ARE NOT OPERATIONAL" : RETURN ST_COMMAND
    TorpedoCourse: ShowDirections() : REM ** DIRECTION HELPER **
    PRINT : LX=5 : PRINT "PHOTON TORPEDO COURSE (1-9) :  "; : GetInput()
    C1=VAL(LII$) : IF C1=9 THEN C1=1
    IF C1>=1 AND C1<9 THEN GOTO TorpedoFire
    PRINT : BACKGROUND 6: COLOR 1: PRINT "ENSIGN CHEKOV REPORTS, INCORRECT"
    PRINT "COURSE DATA, SIR!";:BACKGROUND 0: PRINT : RETURN ST_COMMAND
    TorpedoFire: X1=C(C1,1)+(C(C1+1,1)-C(C1,1))*(C1-INT(C1)) : E=E-2 : P=P-1
    X2=C(C1,2)+(C(C1+1,2)-C(C1,2))*(C1-INT(C1)) : X=S1 : Y=S2
    PRINT : PRINT "TORPEDO TRACKING:"
    TorpedoTrack: X=X+X1 : Y=Y+X2 : X3=INT(X+.5) : Y3=INT(Y+.5)
    IF X3<1 OR X3>8 OR Y3<1 OR Y3>8 THEN GOTO TorpedoMiss
    PRINT " ";X3;",";Y3 : A$=EM$ : Z1=X : Z2=Y : CheckSector()
    IF Z3<>0 THEN GOTO TorpedoTrack
    A$=KS$ : Z1=X : Z2=Y : CheckSector() : IF Z3=0 THEN GOTO TorpedoStar
    PRINT " *** KLINGON DESTROYED ***"
    K3=K3-1 : IF K3>0 THEN PRINT : Pause()
    K9=K9-1 : IFK9<=0 THEN RETURN ST_VICTORY
    FOR I=1 TO 3 : IF X3=K(I,1) AND Y3=K(I,2) THEN GOTO TorpedoKlingonKill
    NEXT I : I=3
    TorpedoKlingonKill: K(I,3)=0 : GOTO TorpedoEnd
    TorpedoStar: A$=SS$ : Z1=X : Z2=Y : CheckSector() : IF Z3=0 THEN GOTO TorpedoBase
    PRINT " ** STAR AT";X3;",";Y3;"ABSORBED TORPEDO **"
    IF K3<>0 THEN PRINT : Pause()
    KlingonsFire()
    IF SHIPDEAD THEN RETURN ST_DEAD
    RETURN ST_COMMAND
    TorpedoBase: A$=BS$ : Z1=X : Z2=Y : CheckSector() : IF Z3=0 THEN GOTO TorpedoCourse
    PRINT " *** STARBASE DESTROYED ***"
    PRINT : Pause()
    B3=B3-1 : B9=B9-1
    IF B9>0 OR K9>T-T0-T9 THEN GOTO CourtMartial
    PRINT : BACKGROUND 6: COLOR 1: PRINT "THAT DOES IT, CAPTAIN!!  YOU ARE HEREBY"
    PRINT "RELIEVED OF COMMAND AND SENTENCED TO 99"
    PRINT "STARDATES AT HARD LABOUR ON CYGNUS 12!!";:BACKGROUND 0
    RETURN ST_MISSIONEND
    CourtMartial: PRINT : PRINT "STARFLEET COMMAND REVIEWING YOUR RECORD"
    PRINT "TO CONSIDER COURT MARTIAL!" : D0=0
    TorpedoEnd: Z1=X : Z2=Y : A$=EM$ : PlaceToken()
    G(Q1,Q2)=K3*100+B3*10+S3 : Z(Q1,Q2)=G(Q1,Q2) : KlingonsFire()
    IF SHIPDEAD THEN RETURN ST_DEAD
    RETURN ST_COMMAND
    TorpedoMiss: PRINT " ** TORPEDO MISSED **"
    IF K3<>0 THEN PRINT : Pause()
    KlingonsFire()
    IF SHIPDEAD THEN RETURN ST_DEAD
    RETURN ST_COMMAND
END FUNCTION


REM ** ===== SHIELD CONTROL ===== **
FUNCTION Shields()
    IF D(7)<0 THEN PRINT : PRINT "SHIELD CONTROL INOPERABLE" : RETURN ST_COMMAND
    PRINT : PRINT "ENERGY AVAILABLE = ";E+S
    LX=5 : PRINT "NUMBER OF UNITS TO SHIELDS :  "; : GetInput()
    X=VAL(LII$)
    IF X<0 OR S=X THEN PRINT "<SHIELDS UNCHANGED>" : RETURN ST_COMMAND
    IF X<=E+S THEN GOTO ShieldsSet
    PRINT :  BACKGROUND 6: COLOR 1: PRINT "SHIELD CONTROL REPORTS THIS IS NOT THE"
    PRINT "FEDERATION TREASURY."
    PRINT "<SHIELDS UNCHANGED>";:BACKGROUND 0: PRINT : RETURN ST_COMMAND
    ShieldsSet: E=E+S-X : S=X : PRINT :BACKGROUND 6: COLOR 1: PRINT "DEFLECTOR CONTROL ROOM REPORT:"
    PRINT "SHIELDS NOW AT ";INT(S);" UNITS PER"
    PRINT "YOUR COMMAND.";:BACKGROUND 0: PRINT : RETURN ST_COMMAND
END FUNCTION


REM ** ===== DAMAGE CONTROL ===== **
FUNCTION Damage()
    IF D(6)>=0 THEN GOTO DamageReport
    PRINT : PRINT "DAMAGE CONTROL REPORT NOT AVAILABLE"
    IF D0=0 THEN RETURN ST_COMMAND
    DamageRepair: D3=0 : FOR I=1 TO 8 : IF D(I)<0 THEN D3=D3+.1
    NEXT I : IF D3=0 THEN RETURN ST_COMMAND
    D3=D3+D4 : IF D3>=1 THEN D3=.9
    PRINT : PRINT "TECHNICIANS STANDING BY TO EFFECT"
    PRINT "REPAIRS TO YOUR SHIP;"
    PRINT "ESTIMATED TIME TO REPAIR: "
    PRINT .01*INT(100*D3);" STARDATES"
    LX=1 : PRINT : PRINT "AUTHORISE THE REPAIR ORDER (Y/N)? "; : GetInput()
    A$=LII$
    IF A$<>"Y" THEN RETURN ST_COMMAND
    FOR I=1 TO 8 : IF D(I)<0 THEN D(I)=0
    NEXT I : T=T+D3+.1
    DamageReport: PRINT : PRINT " SYSTEM              STATE OF REPAIR"
    PRINT      " ------------------- -----------------"
    FOR R1=1 TO 8
    DeviceName() : PRINT " ";G2$;LEFT$(Z$,20-LEN(G2$));
    D2=INT(D(R1)*100)*.01
    IF D2<0 THEN PRINT CCOL$;"DAMAGED     ";D2;FCOL$
    IF D2>0 THEN PRINT "OPERATIONAL ";D2
    IF D2=0 THEN PRINT "OPERATIONAL ";D2
    NEXTR1 : IFD0<>0THEN GOTO DamageRepair
    RETURN ST_COMMAND
END FUNCTION


REM ** ===== KLINGONS SHOOT BACK (SETS SHIPDEAD IF SHIELDS FAIL) ===== **
FUNCTION KlingonsFire()
    SHIPDEAD=0
    IF K3<=0 THEN RETURN
    IF D0<>0 THEN PRINT : PRINT "STARBASE SHIELDS PROTECT THE ENTERPRISE"
    IF D0<>0 THEN RETURN
    FOR I=1 TO 3 : IF K(I,3)<=0 THEN CONTINUE FOR
    H=INT((K(I,3)/FND(1))*(2+RND(1))) : S=S-H : K(I,3)=K(I,3)/(3+RND(0))
    PRINT : PRINT H;" UNIT HIT ENTERPRISE FROM ";K(I,1);",";K(I,2)
    IF S<=0 THEN SHIPDEAD=1 : RETURN
    PRINT " <SHIELDS DOWN TO ";S;" UNITS>" : IF H<20 THEN CONTINUE FOR
    IF RND(1)>.6 OR H/S<=.02 THEN CONTINUE FOR
    R1=FNR(1) : D(R1)=D(R1)-H/S-.5*RND(1) : DeviceName()
    PRINT : BACKGROUND 6: COLOR 1: PRINT "DAMAGE CONTROL REPORTS :  "
    PRINT G2$;" DAMAGED BY THE HIT";:BACKGROUND 0: PRINT
    NEXT I
    ATAKFLAG=1
    RETURN
END FUNCTION


REM ** ===== END-OF-GAME STATES ===== **
FUNCTION ShowGameOver()
    PRINT : PRINT "IT IS STARDATE ";T
    RETURN ST_MISSIONEND
END FUNCTION


FUNCTION ShipDestroyed()
    PRINT : Pause()
    PRINT : PRINT "{RED}THE ENTERPRISE HAS BEEN DESTROYED.{WHITE}"
    PRINT CHR$(13);"THE FEDERATION WILL BE CONQUERED"
    RETURN ST_GAMEOVER
END FUNCTION


FUNCTION ShowMissionEnd()
    PRINT : PRINT "THERE WERE ";K9;" KLINGON BATTLE CRUISERS"
    PRINT "LEFT AT THE END OF YOUR MISSION."
    RETURN ST_PLAYAGAIN
END FUNCTION


FUNCTION AskPlayAgain()
    IF B9=0 THEN RETURN ST_QUIT
    PRINT : PRINT "THE FEDERATION IS IN NEED OF A NEW"
    PRINT "STARSHIP COMMANDER FOR ANOTHER MISSION."
    PRINT : PRINT "... IF THERE IS A VOLUNTEER,"
    LX=3 : PRINT "STEP FORWARD AND ENTER AYE :  "; : GetInput()
    A$=LII$ : IF A$="AYE" THEN RETURN ST_NEWGAME
    RETURN ST_QUIT
END FUNCTION


FUNCTION ShowVictory()
    PRINT : Pause()
    PRINT : PRINT "CONGRATULATIONS, CAPTAIN! THE LAST"
    PRINT "KLINGON BATTLE CRUISER MENACING THE"
    PRINT "FEDERATION HAS BEEN DESTROYED."
    PRINT : PRINT "YOUR EFFICIENCY RATING IS";
    PRINT INT(1000*(K7/(T-T0))^2)
    RETURN ST_PLAYAGAIN
END FUNCTION


REM ** ===== SHORT RANGE SCAN & SUMMARY (SLS CHAINS INTO LRS) ===== **
FUNCTION ShortRangeScan()
    IF ATAKFLAG=1 THEN PRINT : Pause()
    IF D(2)<0 THEN GOTO SrsSensorsOut
    REM
    IF SRSFLAG=0 THEN PRINT : PRINT "{LIGHTBLUE}SHORT RANGE SCAN + SUMMARY DATA{WHITE}"
    SRSFLAG=0 : ATAKFLAG=0
    FOR I=S1-1 TO S1+1 : FOR J=S2-1 TO S2+1
    IF INT(I+.5)<1 OR INT(I+.5)>8 OR INT(J+.5)<1 OR INT(J+.5)>8 THEN CONTINUE FOR
    A$=BS$ : Z1=I : Z2=J : CheckSector() : IF Z3=1 THEN GOTO SrsDocked
    NEXT J : NEXT I : D0=0 : GOTO SrsCondition
    SrsDocked: D0=1 : C$="DOCKED" : E=E0 : P=P0
    PRINT : PRINT "SHIELDS DROPPED FOR DOCKING PURPOSES" : S=0 : GOTO SrsSensorCheck
    SrsCondition: IF K3>0 THEN C$="RED" : GOTO SrsSensorCheck
    C$="GREEN" : IF E<E0*.1 THEN C$="AMBER"
    SrsSensorCheck: IF D(2)>=0 THEN GOTO SrsCombat
    SrsSensorsOut: PRINT : PRINT "*** SHORT RANGE SENSORS ARE OUT ***"
    IF SLSFLAG=1 THEN RETURN Lrs()
    RETURN ST_COMMAND
    SrsCombat: IF K3=0 THEN GOTO SrsGrid
    PRINT : PRINT CCOL$;"COMBAT AREA  ";
    PRINT "** CONDITION RED **";FCOL$
    SrsGrid: LOW$=" LOW!" : PRINT
    PRINT "   {YELLOW}1 2 3 4 5 6 7 8"
    PRINT "  {GREEN}{176}─{178}─{178}─{178}─{178}─{178}─{178}─{178}─┐{WHITE} {LIGHTBLUE}STARDATE{YELLOW}  ";INT(T*10)*.1
    FOR I=1 TO 8
    I$=RIGHT$(STR$(I),1)
    PRINT "{YELLOW}";I$;" {GREEN}{125}{WHITE}"; : REM BORDER
    J1=(I-1)*24+1 : J2=(I-1)*24+22
    FOR J = J1 TO J2 STEP 3
    Z3$=MID$(Q$,J,3)
    IF Z3$="   " THEN PRINT " "; : GOTO SrsGridCell
    PRINT LEFT$(Z3$,1);
    SrsGridCell: IF J=J2 THEN PRINT "{GREEN}{125}{WHITE}";
    IF J<>J2 THEN PRINT "{GREEN}{125}{WHITE}";
    NEXT J
    SELECT CASE I
    CASE 1
        PRINT " {LIGHTBLUE}DAYS LEFT{YELLOW} ";.1*INT((T0+T9-T)*10);
    CASE 2
        PRINT " {LIGHTBLUE}CONDITION{YELLOW} "; : PRINT C$;
    CASE 3
        PRINT " {LIGHTBLUE}QUADRANT  {YELLOW}";Q1;",";Q2;
    CASE 4
        PRINT " {LIGHTBLUE}SECTOR    {YELLOW}";S1;",";S2;
    CASE 5
        PRINT " {LIGHTBLUE}TORPEDOES {YELLOW}";INT(P);
    CASE 6
        PRINT " {LIGHTBLUE}ENERGY    {YELLOW}";INT(E+S);
    CASE 7
        PRINT " {LIGHTBLUE}SHIELDS   {YELLOW}";INT(S);
        IF S<201 AND K3>0 THEN PRINT LOW$;
    CASE 8
        PRINT " {LIGHTBLUE}KLINGONS  {YELLOW}";INT(K9);
    END SELECT
    PRINT
    NEXT I : PRINT "  {GREEN}{173}─{177}─{177}─{177}─{177}─{177}─{177}─{177}─{189}{WHITE}";
    MW=E/8 : MW=MW*10 : MW=INT(MW) : MW=MW/10
    IF MW>8 THEN MW=8
    IF D(1)<0 AND MW>0.2 THEN MW=0.2
    PRINT " {LIGHTBLUE}MAX WARP{YELLOW}  ";MW
    IF SLSFLAG=1 THEN RETURN Lrs()
    RETURN ST_COMMAND
END FUNCTION


REM ** ===== LIBRARY COMPUTER ===== **
FUNCTION Computer()
    IFD(8)<0THEN PRINT : PRINT "SHIPS COMPUTER DISABLED" : RETURN ST_COMMAND
    PRINT : PRINT "FUNCTIONS AVAILABLE FROM COMPUTER:" : PRINT
    PRINT " 0 - CUMULATIVE GALACTIC RECORD"
    PRINT " 1 - STATUS & DAMAGE REPORT"
    PRINT " 2 - PHOTON TORPEDO TARGETING DATA"
    PRINT " 3 - STARBASE NAV DATA"
    PRINT " 4 - DIRECTION/DISTANCE CALCULATOR"
    PRINT " 5 - GALAXY REGION NAME MAP"
    PRINT : LX=1 : PRINT CHR$(13);"COMPUTER ACTIVE & AWAITING COMMAND :  ";
    IF COMFLAG=1 THEN PRINT "0" : A=0 : GOTO ComputerDispatch
    GetInput()
    A=VAL(LII$) : A1=A : IFA<0 OR A>5THEN RETURN ST_COMMAND
    IF LII$="" THEN RETURN ST_COMMAND
    ComputerDispatch: H8=1
    SELECT CASE A
    CASE 0
        GOTO GalacticRecord
    CASE 1
        GOTO StatusReport
    CASE 2
        GOTO NavCalcKlingon
    CASE 3
        GOTO BaseNav
    CASE 4
        GOTO Calculator
    CASE 5
        GOTO GalaxyMap
    END SELECT
    REM SETUP TO CHANGE CUM GAL RECORD TO GALAXY MAP
    GalaxyMap: H8=0 : G5=1 : PRINT : PRINT "{CLR}{REVERSE ON}THE GALAXY:{REVERSE OFF}" : PRINT : PRINT "   "; : GOTO GalHeader
    REM CUM GALACTIC RECORD
    GalacticRecord: PRINT : GALFLAG=0
    PRINT "{CLR}{REVERSE ON}COMPUTER RECORD OF GALAXY FOR " : PRINT "QUADRANT ";Q1;",";Q2 : PRINT "{REVERSE OFF}"
    PRINT CHR$(13);: PRINT "   ";
    GalHeader: FOR J=1 TO 8 : J$=STR$(J) : J$=RIGHT$(J$,1)
    IF A1=5 THEN RomanNumeral() : CONTINUE FOR
    IF J=Q2 THEN PRINT " {WHITE}";J$;"{GREEN}  ";
    IF J<>Q2 THEN PRINT " {GREEN}";J;"{GREEN}  ";
    NEXT J
    PRINT
    O1$="  ┌───┬───┬───┬───┬───┬───┬───┬───┐"
    O2$="  ├───┼───┼───┼───┼───┼───┼───┼───┤"
    PRINT O1$ : FOR I=1 TO 8 : I$=STR$(I) : I$=RIGHT$(I$,1)
    IF I=Q1 THEN PRINT " ";I$;"";
    IF A1=5 AND I=Q1 THEN GOTO GalRegionRow
    IF I<>Q1 THEN PRINT " ";I$; : IFH8=0THEN GOTO GalRegionRow
    FOR J=1 TO 8
    IF I=Q1 AND J=Q2 THEN PRINT "{221}"; : GALFLAG=1 : GOTO GalCell
    IF I=Q1 AND J-1=Q2 THEN GOTO GalCell
    IF I<>Q1 OR J<>Q2 THEN PRINT "{221}";
    GalCell: IFZ(I,J)=0THEN PRINT "   "; : CONTINUE FOR
    G1$=RIGHT$(STR$(Z(I,J)+1000),3)
    G2$=ECOL$+MID$(G1$,1,1) : PRINT G2$;
    G2$=DCOL$+MID$(G1$,2,1) : PRINT G2$;
    G2$=HCOL$+MID$(G1$,3,1) : PRINT G2$;FCOL$;
    IF GALFLAG=1 THEN PRINT "{221}"; : GALFLAG=0
    NEXT J : GOTO GalRowEnd
    GalRegionRow: Z4=I : Z5=1 : QuadrantName() : J0=INT(11-.5*LEN(G2$))
    PRINT "{221}";
    PRINT TAB(J0);G2$;
    PRINT TAB(18);"{221}";
    Z5=5 : QuadrantName() : J0=INT(27-.5*LEN(G2$))
    PRINT TAB(J0);G2$; : PRINT TAB(34);"{221}";
    GalRowEnd: IF A=0 AND J=9 AND Q1=I AND Q2=8 THEN PRINT : GOTO GalRowA5
    IF A=0 THEN PRINT "{221}"
    GalRowA5: IF A=5 THEN PRINT
    IF I<8 THEN PRINT O2$ : NEXT I
    PRINT "  {173}{45}{178}─{177}───{177}───{177}───{177}───{177}───{177}───{177}───{189}" : A1=0 : RETURN ST_COMMAND
    StatusReport: PRINT : PRINT "{CLR}{REVERSE ON}STATUS REPORT:{REVERSE OFF}";CHR$(13) : X$="" : IF K9>1 THEN X$="S"
    PRINT : PRINT " KLINGONS LEFT :";K9
    PRINT " ENERGY        :";INT(E+S)
    PRINT " TORPEDOES     :";INT(P)
    PRINT : PRINT "{13} MISSION MUST BE COMPLETED IN ";.1*INT((T0+T9-T)*10)
    PRINT " STARDATES"
    X$="S" : IFB9<2THENX$="" : IFB9<1THEN GOTO StatusNoBase
    PRINT : PRINT "{13} THE FEDERATION IS MAINTAINING ";B9
    PRINT " STARBASE";X$;" IN THE GALAXY"; CHR$(13)
    RETURN Damage()
    StatusNoBase: PRINT : PRINT "{13}YOUR STUPIDITY HAS LEFT YOU ON YOUR OWN"
    PRINT "IN THE GALAXY -- YOU HAVE NO STARBASES"
    PRINT "LEFT!" : RETURN Damage()
    NavCalcKlingon: IFK3<=0THEN NoEnemyMsg() : RETURN ST_COMMAND
    X$="" : IFK3>1THENX$="S"
    PRINT : PRINT "FROM ENTERPRISE TO KLINGON SHIP";
    PRINT X$
    H8=0 : FORI=1TO3 : IFK(I,3)<=0THEN GOTO CalcDone
    W1=K(I,1) : X=K(I,2)
    NavCalcFrom: C1=S1 : A=S2 : GOTO CalcCompute
    Calculator: PRINT : PRINT "DIRECTION/DISTANCE CALCULATOR:"
    PRINT : PRINT "YOU ARE AT QUADRANT ";Q1;",";Q2
    PRINT "             SECTOR ";S1;",";S2
    PRINT : LX=4 : PRINT "ENTER INITIAL COORDINATES (Y) :  "; : GetInput()
    C1=VAL(LII$) : IF C1=0 THEN PRINT : PRINT "CALCULATION ABORTED!" : RETURN ST_COMMAND
    LX=4 : PRINT "ENTER INITIAL COORDINATES (X) :  "; : GetInput()
    A=VAL(LII$) : IF A=0 THEN PRINT : PRINT "CALCULATION ABORTED!" : RETURN ST_COMMAND
    PRINT : LX=4 : PRINT "ENTER FINAL COORDINATES   (Y) :  "; : GetInput()
    W1=VAL(LII$) : IF W1=0 THEN PRINT : PRINT "CALCULATION ABORTED!" : RETURN ST_COMMAND
    PRINT : LX=4 : PRINT "ENTER FINAL COORDINATES   (X) :  "; : GetInput()
    X=VAL(LII$) : IF X=0 THEN PRINT : PRINT "CALCULATION ABORTED!" : RETURN ST_COMMAND
    IF C1=W1 AND A=X THEN PRINT : PRINT "NO RESULTS POSSIBLE!" : RETURN ST_COMMAND
    CalcCompute: X=X-A : A=C1-W1 : IFX<0THEN GOTO CalcDirC
    IFA<0THEN GOTO CalcDir7
    IFX>0THEN GOTO CalcDir1
    IFA=0THENC1=5 : GOTO CalcDirA
    CalcDir1: C1=1
    CalcDirA: IFABS(A)<=ABS(X)THEN GOTO CalcDirB
    PRINT : PRINT " DIRECTION =";
    D2=C1+(((ABS(A)-ABS(X))+ABS(A))/ABS(A))
    D2=D2*1000 : D2=D2+0.5 : D2=INT(D2) : D2=D2/1000
    PRINT D2 : GOTO CalcDistance
    CalcDirB: PRINT : PRINT " DIRECTION =";
    D2=C1+(ABS(A)/ABS(X))
    D2=D2*1000 : D2=D2+0.5 : D2=INT(D2) : D2=D2/1000
    PRINT D2 : GOTO CalcDistance
    CalcDirC: IFA>0THENC1=3 : GOTO CalcDirD
    IFX<>0THENC1=5 : GOTO CalcDirA
    CalcDir7: C1=7
    CalcDirD: IFABS(A)>=ABS(X)THEN GOTO CalcDirE
    PRINT : PRINT " DIRECTION =";
    D2=C1+(((ABS(X)-ABS(A))+ABS(X))/ABS(X))
    D2=D2*1000 : D2=D2+0.5 : D2=INT(D2) : D2=D2/1000
    PRINT D2 : GOTO CalcDistance
    CalcDirE: PRINT : PRINT " DIRECTION =";
    D2=C1+(ABS(X)/ABS(A))
    D2=D2*1000 : D2=D2+0.5 : D2=INT(D2) : D2=D2/1000
    PRINT D2
    CalcDistance: PRINT " DISTANCE  =";
    D2=SQR(X^2+A^2)
    IF A1=3 OR A1=2 THEN D2=D2/10
    D2=D2*1000 : D2=D2+0.5 : D2=INT(D2) : D2=D2/1000
    PRINT D2
    IFH8=1THEN RETURN ST_COMMAND
    CalcDone: NEXTI : RETURN ST_COMMAND
    BaseNav: IFB3<>0THEN PRINT : PRINT "FROM ENTERPRISE TO STARBASE" : W1=B4 : X=B5 : GOTO NavCalcFrom
    PRINT : PRINT "MR. SPOCK REPORTS, SENSORS SHOW NO"
    PRINT "STARBASES IN THIS QUADRANT." : RETURN ST_COMMAND
END FUNCTION


REM ** ===== SHARED MESSAGE: NO ENEMY IN QUADRANT ===== **
FUNCTION NoEnemyMsg()
    PRINT : BACKGROUND 6: COLOR 1: PRINT "SCIENCE OFFICER SPOCK REPORTS SENSORS"
    PRINT "SHOW NO ENEMY SHIPS IN THIS QUADRANT";:BACKGROUND 0: PRINT
    RETURN
END FUNCTION


REM FIND EMPTY PLACE IN QUADRANT (FOR THINGS)
FUNCTION FindEmpty()
    REM ** RETRY UNTIL CHECKSECTOR REPORTS THE SQUARE IS EMPTY (Z3<>0) **
    DO
    A$=EM$
    R1=FNR(1) : R2=FNR(1) : Z1=R1 : Z2=R2
    CheckSector()
    LOOP UNTIL Z3<>0
    RETURN
END FUNCTION


REM INSERT IN STRING ARRAY FOR QUADRANT
FUNCTION PlaceToken()
    S8 = INT(Z2-0.5) * 3 + INT(Z1-0.5) * 24 + 1
    IF LEN(A$)<>3 THEN PRINT "TOKEN LENGTH ERROR: ";A$;" LEN=";LEN(A$) : STOP
    IFS8=1THENQ$=A$+RIGHT$(Q$,189) : RETURN
    IFS8=190THENQ$=LEFT$(Q$,189)+A$ : RETURN
    Q$=LEFT$(Q$,S8-1)+A$+RIGHT$(Q$,190-S8) : RETURN
END FUNCTION


REM PRINTS DEVICE NAME -- SELECT CASE LOOKUP, NO GOTOS
FUNCTION DeviceName()
    SELECT CASE R1
    CASE 1
        G2$="WARP ENGINES"
    CASE 2
        G2$="SHORT RANGE SENSORS"
    CASE 3
        G2$="LONG RANGE SENSORS"
    CASE 4
        G2$="PHASER CONTROL"
    CASE 5
        G2$="PHOTON TUBES"
    CASE 6
        G2$="DAMAGE CONTROL"
    CASE 7
        G2$="SHIELD CONTROL"
    CASE 8
        G2$="LIBRARY-COMPUTER"
    END SELECT
    RETURN
END FUNCTION


REM STRING COMPARISON IN QUADRANT ARRAY
FUNCTION CheckSector()
    Z1=INT(Z1+.5) : Z2=INT(Z2+.5) : S8=(Z2-1)*3+(Z1-1)*24+1 : Z3=0
    IFMID$(Q$,S8,3)<>A$THENRETURN
    Z3=1 : RETURN
END FUNCTION


REM QUADRANT NAME IN G2$ FROM Z4,Z5 (=Q1,Q2)
REM CALL WITH G5=1 TO GET REGION NAME ONLY
FUNCTION QuadrantName()
    REM ** REGIONS 1-4 OF EACH ROW USE THE FIRST NAME, 5-8 THE SECOND **
    SELECT CASE Z4
    CASE 1
        G2$="ANTARES" : IF Z5>4 THEN G2$="SIRIUS"
    CASE 2
        G2$="RIGEL" : IF Z5>4 THEN G2$="DENEB"
    CASE 3
        G2$="PROCYON" : IF Z5>4 THEN G2$="CAPELLA"
    CASE 4
        G2$="VEGA" : IF Z5>4 THEN G2$="BETELGEUSE"
    CASE 5
        G2$="CANOPUS" : IF Z5>4 THEN G2$="ALDEBARAN"
    CASE 6
        G2$="ALTAIR" : IF Z5>4 THEN G2$="REGULUS"
    CASE 7
        G2$="SAGITTARIUS" : IF Z5>4 THEN G2$="ARCTURUS"
    CASE 8
        G2$="POLLUX" : IF Z5>4 THEN G2$="SPICA"
    END SELECT
    IF G5=1 THEN RETURN
    SELECT CASE Z5
    CASE 1, 5
        G2$=G2$+" I"
    CASE 2, 6
        G2$=G2$+" II"
    CASE 3, 7
        G2$=G2$+" III"
    CASE 4, 8
        G2$=G2$+" IV"
    END SELECT
    RETURN
END FUNCTION


REM ** GET INPUT **
REM GET CHARACTERS UNTIL RETURN IS PRESSED
REM THEN RETURN 
FUNCTION GetInput()
    REM ** LX = MAX INPUT  LII$ = OUTPUT STRING **
    REM PRINT "> ";
    LII$=""
    DO 
        GET Y$
        Y$=UCASE$(Y$)
        IF Y$="" THEN CONTINUE DO
        IF ASC(Y$)=0 THEN Y$=CHR$(13)

        IF ASC(Y$)=13 AND LX=0 THEN PRINT "{CLR}": PRINT FCOL$ : RETURN
        IF ASC(Y$)=13 THEN PRINT : PRINT FCOL$ : RETURN

        IF ASC(Y$)=20 AND LEN(LII$)<1 THEN CONTINUE DO
        IF Y$=CHR$(20) THEN Y$="" : LII$=LEFT$(LII$,(LEN(LII$)-1))

        IF ASC(Y$)<>32 AND (ASC(Y$)<46 OR ASC(Y$)>90) THEN CONTINUE DO

        IF LEN(LII$)<LX THEN PRINT Y$;
        IF LEN(LII$)<LX THEN LII$=LII$+Y$
    LOOP
END FUNCTION


FUNCTION Pause()
    REM ** PAUSE WITHOUT CR**
    IF CRSTART=1 THEN CR$="PRESS RETURN TO BEGIN"
    IF CRSTART=0 THEN CR$="PRESS RETURN TO CONTINUE"
    LX=0 : PRINT "{REVERSE ON}{LIGHTBLUE}":PRINT CR$:PRINT "{REVERSE OFF}{WHITE}" : GetInput()
    CRSTART=0
    RETURN
END FUNCTION

REM ** KEY TO SRS ICONS **
FUNCTION ShowKey()
    PRINT : PRINT "{13}KEY TO SHORT RANGE SCANNER ICONS:" : PRINT
    PRINT " {CYAN}E{WHITE} = THE USS ENTERPRISE"
    PRINT " {CYAN}B{WHITE} = FEDERATION STARBASE"
    PRINT " {CYAN}*{WHITE} = STAR"
    PRINT " {CYAN}K{WHITE} = KLINGON BATTLE CRUISER"
    RETURN
END FUNCTION

REM ** LIST OF COMMANDS **
FUNCTION ShowCommands()
    PRINT : PRINT "{13}USE THESE COMMANDS:" : PRINT
    PRINT " {CYAN}NAV{WHITE} - TO SET COURSE"
    PRINT " {CYAN}SRS{WHITE} - FOR SHORT RANGE SCAN"
    PRINT " {CYAN}LRS{WHITE} - FOR LONG RANGE SCAN"
    PRINT " {CYAN}SLS{WHITE} - FOR SHORT & LONG RANGE SCAN"
    PRINT " {CYAN}PHA{WHITE} - TO FIRE PHASERS"
    PRINT " {CYAN}TOR{WHITE} - TO FIRE PHOTON TORPEDOES"
    PRINT " {CYAN}SHE{WHITE} - TO RAISE OR LOWER SHIELDS"
    PRINT " {CYAN}DAM{WHITE} - FOR DAMAGE CONTROL REPORTS"
    PRINT " {CYAN}COM{WHITE} - TO CALL ON LIBRARY-COMPUTER"
    PRINT " {CYAN}KEY{WHITE} - DISPLAY KEY TO SRS ICONS"
    PRINT " {CYAN}HLP{WHITE} - THIS LIST OF COMMANDS"
    PRINT " {CYAN}XXX{WHITE} - TO RESIGN YOUR COMMAND"
    RETURN
END FUNCTION

REM ** DIRECTION HELPER **
FUNCTION ShowDirections()
    PRINT ""
    PRINT " ENTER A NUMBER       4  3  2"
    PRINT " BETWEEN 1 AND 9       . . ."
    PRINT "                        ..."
    PRINT " DECIMALS MAY BE    5 ---*--- 1"
    PRINT " USED (EG. 8.57)        ..."
    PRINT "                       . . ."
    PRINT "                      6  7  8"
    RETURN
END FUNCTION

REM ** GALAXY MAP ROMAN NUMERALS **
FUNCTION RomanNumeral()

    PRINT "";
    SELECT CASE J
    CASE 1, 5
        PRINT " I ";;
    CASE 2, 6
        PRINT "II ";
    CASE 3, 7
        PRINT "III";
    CASE 4, 8
        PRINT "IV ";
    END SELECT
    PRINT " "; : RETURN
END FUNCTION

REM ** COLOURS FOR IN-GAME **
FUNCTION InitColours()
    ACOL$="{BLACK}" : REM CHR$(144) : REM 144 = (00) BLACK
    BCOL$="{WHITE}" : REM CHR$(005) : REM 005 = (01) WHITE
    CCOL$="{RED}" : REM CHR$(028) : REM 028 = (02) RED
    DCOL$="{CYAN}" : REM CHR$(159) : REM 159 = (03) CYAN
    ECOL$="{PINK}" : REM CHR$(156) : REM 156 = (04) VIOLET
    FCOL$="{GREEN}" : REM CHR$(030) : REM 030 = (05) GREEN
    GCOL$="{BLUE}" : REM CHR$(031) : REM 031 = (06) BLUE
    HCOL$="{YELLOW}" : REM CHR$(158) : REM 158 = (07) YELLOW
    ICOL$="{ORANGE}" : REM CHR$(129) : REM 129 = (08) ORANGE
    REM ** COLOURS FOR INITIALISATION **
    REM POKE 53280,0 : POKE 53281,0 : POKE 646,5 : RETURN
    RETURN
END FUNCTION


