#OPTION PETSCII
SCREENCODES ON : BACKGROUND 0
REM ** SUPER STAR TREK -- STRUCTURED (STATE-MACHINE) VERSION
REM ** BY MIKE MAYFIELD 1974
REM ** MODIFIED BY DAVID AHL 1978
REM ** CONVERTED TO 40 COLUMNS
REM ** BY ELECTRON.GREG 2022-2023
REM ** MODIFIED BY CHRIS GARRETT 2025
REM ** ( FOR TUTORIAL USE )
REM ** SUPPORT ELECTRON.GREG
REM ** https://electrongreg.itch.io/
REM **
REM ** THE WHOLE GAME IS NOW DRIVEN BY ONE STATE LOOP (BELOW). EACH STATE
REM ** IS A FUNCTION THAT DOES ITS WORK AND RETURNS THE NEXT STATE, SO
REM ** THERE ARE NO GOTOS BETWEEN ROUTINES


ST_QUIT=0 : ST_NEWGAME=1 : ST_NEWQUAD=2 : ST_COMMAND=3 : ST_DEAD=4
ST_GAMEOVER=5 : ST_VICTORY=6 : ST_MISSIONEND=7 : ST_PLAYAGAIN=8
ENTERPRISE_TOKEN$="E  " : KLINGON_TOKEN$="K  " : STARBASE_TOKEN$="B  " : STAR_TOKEN$="*  " : EMPTY_TOKEN$="   "
A1$="NAVSRSLRSPHATORSHEDAMCOMXXXHLP"
InitColours()
REM COURSE_VEC(9,2) = nav keypad deltas (course n -> dx, dy); DEVICE_DAMAGE(8) = stardates-to-repair per system
DIM G(8,8),COURSE_VEC(9,2),K(3,3),N(3),Z(8,8),DEVICE_DAMAGE(8)

REM ** DISTANCE CALCULATION **
REM Uses the Pythagorean theorem to calculate the distance between two points.
DEF FND(D)=SQR((K(I,1)-SECTOR_X)^2+(K(I,2)-SECTOR_Y)^2)

REM ** RANDOM NUMBER GENERATOR **
REM Generates a random number between 1 and 8.
REM R is the random number generator seed.
DEF FNR(R)=INT(RND(R)*7.98+1.01)


REM ** ===== MAIN STATE LOOP ===== **
REM ** EACH STATE FUNCTION DOES ITS WORK AND RETURNS THE NEXT STATE. WE
REM ** DISPATCH WITH A SELECT CASE AND REPEAT UNTIL A FUNCTION HANDS BACK
REM ** ST_QUIT. NO GOTOS HERE AT ALL -- JUST A DO/LOOP + SELECT CASE. **
GameState = ST_NEWGAME
DO
  SELECT CASE GameState
    CASE ST_NEWGAME
      GameState = SetupGame()
    CASE ST_NEWQUAD
      GameState = EnterQuadrant()
    CASE ST_COMMAND
      GameState = DoCommand()
    CASE ST_DEAD
      GameState = ShipDestroyed()
    CASE ST_GAMEOVER
      GameState = ShowGameOver()
    CASE ST_VICTORY
      GameState = ShowVictory()
    CASE ST_MISSIONEND
      GameState = ShowMissionEnd()
    CASE ST_PLAYAGAIN
      GameState = AskPlayAgain()
  END SELECT
LOOP UNTIL GameState = ST_QUIT
END



REM ** ===== ONE-TIME GAME SETUP (NEW GAME / RESTART) ===== **
FUNCTION SetupGame()
    Z2$=""
    ATAKFLAG=0
    SLSFLAG=0
    N=RND(-1)
    PRINT CHR$(147);
    PRINT HCOL$;"{YELLOW}   --S-U-P-E-R---S-T-A-R---T-R-E-K--"
    PRINT "{WHITE}"
    FOR N=1 TO 5
      PRINT
    NEXT
    PRINT BCOL$;
    PRINT "                    ,------*-------,"
    PRINT "    ,-------------,  '---  -------'"
    PRINT "    '--------{109}{109}--'      / /"
    PRINT "          ,---{109}{109}-------/ /--,"
    PRINT "          '----------------'"
    PRINT DCOL$
    PRINT "    THE USS ENTERPRISE --- NCC-1701"
    FOR N=1 TO 5
      PRINT FCOL$
    NEXT
    CRSTART=1
    Pause()
    RANDOM_SEED=RND(-TI) : REM ** RANDOM SEED GENERATOR **
    PRINT : PRINT "{CLR}           GENERATING GALAXY";
    SPACE_PAD$="                         "
    STARDATE_CUR=INT(RND(1)*20+20)*100
    STARDATE_START=STARDATE_CUR
    MISSION_DAYS=25+INT(RND(1)*10)
    D0=0
    SHIP_ENERGY=3000
    ENERGY_MAX=SHIP_ENERGY
    TORPEDO_COUNT=10
    TORPEDO_MAX=TORPEDO_COUNT
    KLINGON_HP_BASE=200
    SHIELD_UNITS=0
    STARBASE_COUNT=2
    KLINGON_COUNT=0
    X$=""
    X0$=" IS "
    REM INITIALIZE ENTERPRISES POSITION
    QUADRANT_X=FNR(1)
    QUADRANT_Y=FNR(1)
    SECTOR_X=FNR(1)
    SECTOR_Y=FNR(1)
    FOR I=1 TO 9
      COURSE_VEC(I,1)=0
      COURSE_VEC(I,2)=0
    NEXT I
    COURSE_VEC(3,1)=-1 : COURSE_VEC(2,1)=-1 : COURSE_VEC(4,1)=-1 : COURSE_VEC(4,2)=-1 : COURSE_VEC(5,2)=-1 : COURSE_VEC(6,2)=-1
    COURSE_VEC(1,2)=1 : COURSE_VEC(2,2)=1 : COURSE_VEC(6,1)=1 : COURSE_VEC(7,1)=1 : COURSE_VEC(8,1)=1 : COURSE_VEC(8,2)=1 : COURSE_VEC(9,2)=1
    FOR I=1 TO 8
      DEVICE_DAMAGE(I)=0
    NEXT I
    REM SETUP WHAT EXISTS IN GALAXY . . .
    REM K3= # KLINGONS  B3= # STARBASES  S3 = # STARS
    FOR I=1 TO 8
      PRINT ".";
      FOR J=1 TO 8
        K3=0
        Z(I,J)=0
        RAND_ROLL=RND(1)
        SELECT CASE RAND_ROLL
        CASE IS > .98
        K3=3 : KLINGON_COUNT=KLINGON_COUNT+3
        CASE IS > .95
        K3=2 : KLINGON_COUNT=KLINGON_COUNT+2
        CASE IS > .80
        K3=1 : KLINGON_COUNT=KLINGON_COUNT+1
        END SELECT
        B3=0
        IF RND(1)>.96 THEN B3=1 : STARBASE_COUNT=STARBASE_COUNT+1
        G(I,J)=K3*100+B3*10+FNR(1)
      NEXT J
    NEXT I
    IF KLINGON_COUNT>MISSION_DAYS THEN MISSION_DAYS=KLINGON_COUNT+1
    PRINT
    ShowKey() : REM ** KEY TO SRS ICONS **
    ShowCommands() : REM ** USE THESE COMMANDS LIST **
    PRINT
    Pause() : REM ** PAUSE **
    REM Guarantee at least one starbase and preserve original balancing tweak.
    IF STARBASE_COUNT=0 THEN
      IF G(QUADRANT_X,QUADRANT_Y)<200 THEN G(QUADRANT_X,QUADRANT_Y)=G(QUADRANT_X,QUADRANT_Y)+120 : KLINGON_COUNT=KLINGON_COUNT+1
      STARBASE_COUNT=1
      G(QUADRANT_X,QUADRANT_Y)=G(QUADRANT_X,QUADRANT_Y)+10
      QUADRANT_X=FNR(1)
      QUADRANT_Y=FNR(1)
    END IF
    K7=KLINGON_COUNT
    IF STARBASE_COUNT<>1 THEN X$="S" : X0$=" ARE "
    PRINT
    PRINT "{CLR}{REVERSE ON}YOUR ORDERS ARE AS FOLLOWS:{REVERSE OFF}"
    PRINT
    PRINT "DESTROY THE ";KLINGON_COUNT;" KLINGON WARSHIPS BEFORE"
    PRINT "STARDATE ";STARDATE_START+MISSION_DAYS;". THIS GIVES YOU ";MISSION_DAYS;" DAYS."
    PRINT "THERE";X0$;STARBASE_COUNT;" STARBASE";X$;" IN THE GALAXY"
    PRINT "FOR RESUPPLYING & REPAIRING YOUR SHIP."
    I=RND(1)
    RETURN ST_NEWQUAD
END FUNCTION




REM ** ===== ENTER A QUADRANT: SET IT UP, PLACE OBJECTS, SHORT SCAN ===== **
FUNCTION EnterQuadrant()
    Z4=QUADRANT_X
    Z5=QUADRANT_Y
    K3=0 : B3=0 : S3=0
    G5=0
    D4=.5*RND(1)
    Z(QUADRANT_X,QUADRANT_Y)=G(QUADRANT_X,QUADRANT_Y)
    IF QUADRANT_X >= 1 AND QUADRANT_X <=8 AND QUADRANT_Y>=1 AND QUADRANT_Y<=8 THEN
      QuadrantName()
      PRINT
    IF STARDATE_START=STARDATE_CUR THEN
      PRINT "YOUR MISSION BEGINS WITH YOUR STARSHIP"
      PRINT "IN THE QUADRANT, ";G2$;"."
      SRSFLAG=1
      PRINT
      Pause() : REM ** PAUSE **
      PRINT
    ELSE
      IF ATAKFLAG=1 THEN
        Pause()
        ATAKFLAG=0
        PRINT
      END IF
      SRSFLAG=1
      PRINT "ENTERING ";G2$;" QUADRANT..."
    END IF
    END IF
    REM Decode G(quad): K3/B3/S3 = klingons / starbases / stars in this quadrant
    K3=INT(G(QUADRANT_X,QUADRANT_Y)*.01)
    B3=INT(G(QUADRANT_X,QUADRANT_Y)*.1)-10*K3
    S3=G(QUADRANT_X,QUADRANT_Y)-100*K3-10*B3
    FOR I=1 TO 3
      K(I,1)=0
      K(I,2)=0
    NEXT I
    FOR I=1 TO 3
      K(I,3)=0
    NEXT I
    QUADRANT_BUFFER$=SPACE_PAD$+SPACE_PAD$+SPACE_PAD$+SPACE_PAD$+SPACE_PAD$+SPACE_PAD$+SPACE_PAD$+LEFT$(SPACE_PAD$,17)
    REM POSITION ENTERPRISE IN QUADRANT, THEN PLACE "K3" KLINGONS, &
    REM "B3" STARBASES, & "S3" STARS ELSE WHERE.
    A$=ENTERPRISE_TOKEN$
    TOKEN_X=SECTOR_X
    TOKEN_Y=SECTOR_Y
    PlaceToken()
    IF K3 >= 1 THEN
      FOR I=1 TO K3
        FindEmpty()
        A$=KLINGON_TOKEN$
        TOKEN_X=RANDOM_X : TOKEN_Y=RANDOM_Y
        PlaceToken()
        K(I,1)=RANDOM_X : K(I,2)=RANDOM_Y : K(I,3)=KLINGON_HP_BASE*(0.5+RND(1))
      NEXT I
    END IF
    IF B3 >= 1 THEN
      FindEmpty()
      A$=STARBASE_TOKEN$
      TOKEN_X=RANDOM_X : B4=RANDOM_X
      TOKEN_Y=RANDOM_Y : B5=RANDOM_Y
      PlaceToken()
    END IF
    FOR I=1 TO S3
      FindEmpty()
      A$=STAR_TOKEN$
      TOKEN_X=RANDOM_X : TOKEN_Y=RANDOM_Y
      PlaceToken()
    NEXT I
    RETURN ShortRangeScan()
END FUNCTION




REM ** ===== COMMAND PHASE: ENERGY CHECK, PROMPT, DISPATCH ONE COMMAND ===== **
FUNCTION DoCommand()
    IF SHIELD_UNITS+SHIP_ENERGY <= 10 OR (SHIP_ENERGY<=10 AND DEVICE_DAMAGE(7)<>0) THEN
      PRINT : PRINT "** FATAL ERROR **"
      PRINT "YOUVE STRANDED YOUR SHIP IN SPACE."
      PRINT "YOU HAVE INSUFFICIENT MANOEUVRING"
      PRINT "ENERGY, & SHIELD CONTROL IS PRESENTLY"
      PRINT "INCAPABLE OF CROSS-CIRCUITING TO"
      PRINT "ENGINE ROOM!!"
      PRINT : Pause()
      RETURN ST_GAMEOVER
    END IF
    DO
      PRINT
      SRSFLAG=0
      LX=3
      PRINT "{13}{REVERSE ON}{LIGHTBLUE}COMMAND:{REVERSE OFF}{WHITE} ";
      GetInput()
      A$=LII$ : Z2$=A$ : ATAKFLAG=0
      IF A$="SLS" THEN SLSFLAG=1
      IF A$="SLS" THEN PRINT : PRINT "{CLR}{REVERSE ON}SHORT & LONG RANGE SCAN...{REVERSE OFF}" : RETURN ShortRangeScan()
      IF A$="KEY" THEN ShowKey() : REM KEY TO SRS ICONS
      IF A$="KEY" THEN CONTINUE DO
      COMFLAG=0
      IF A$="GAL" AND DEVICE_DAMAGE(8)>=0 THEN A$="COM" : COMFLAG=1
      IF DEVICE_DAMAGE(8)<0 AND A$="GAL" THEN PRINT : PRINT "SHIPS COMPUTER DISABLED" : CONTINUE DO
      CMD=0 : FOR I=1 TO 10 : IF LEFT$(A$,3)=MID$(A1$,3*I-2,3) THEN CMD=I
      NEXT I
      SELECT CASE CMD
      CASE 1
          RETURN Nav()
      CASE 2
          RETURN ShortRangeScan()
      CASE 3
          RETURN Lrs()
      CASE 4
          RETURN Phasers()
      CASE 5
          RETURN Torpedo()
      CASE 6
          RETURN Shields()
      CASE 7
          RETURN Damage()
      CASE 8
          RETURN Computer()
      CASE 9
          RETURN ST_MISSIONEND
      END SELECT
      ShowCommands()
    LOOP
END FUNCTION




REM ** ===== COURSE CONTROL (NAV) ===== **
FUNCTION Nav()
    ShowDirections() : REM ** DIRECTION HELPER **
    PRINT : LX=5 : PRINT "COURSE (1-9) :  "; : GetInput()
    C1=VAL(LII$) : IF C1=9 THEN C1=1
    IF C1<1 OR C1>=9 THEN
    BACKGROUND 6: COLOR 1
    PRINT : PRINT "LT. SULU REPORTS, INCORRECT COURSE"
    PRINT "DATA, SIR!";: BACKGROUND 0: PRINT
    RETURN ST_COMMAND
    END IF
    X$="8"
    IF DEVICE_DAMAGE(1)<0 THEN X$="0.2"
    SRSFLAG=1
    LX=5
    PRINT "WARP FACTOR (0-";X$;") :  ";
    GetInput()
    NAV_WARP_FACTOR=VAL(LII$)
    IF DEVICE_DAMAGE(1)<0 AND NAV_WARP_FACTOR>.2 THEN
    PRINT : PRINT "WARP ENGINES ARE DAMAGED."
    PRINT "MAXIMUM SPEED = WARP 0.2" : RETURN ST_COMMAND
    END IF
    IF NAV_WARP_FACTOR>0 AND NAV_WARP_FACTOR<=8 THEN
      N=INT(NAV_WARP_FACTOR*8+.5)
    IF SHIP_ENERGY-N<0 THEN
    PRINT : BACKGROUND 6: COLOR 1:PRINT "ENGINEERING REPORTS INSUFFICIENT ENERGY";
    PRINT "AVAILABLE FOR WARP ";NAV_WARP_FACTOR;"!";: BACKGROUND 0
    IF SHIELD_UNITS < N-SHIP_ENERGY OR DEVICE_DAMAGE(7) < 0 THEN RETURN ST_COMMAND
    PRINT :BACKGROUND 6: COLOR 1: PRINT "DEFLECTOR CONTROL ROOM ACKNOWLEDGES"
    S1$=STR$(SHIELD_UNITS)
    PRINT "SHIELD ENERGY DEPLOYED IS ";S1$;" UNITS.";: BACKGROUND 0
    RETURN ST_COMMAND
    END IF
    ELSE
    IF NAV_WARP_FACTOR=0 THEN RETURN ST_COMMAND
    PRINT : BACKGROUND 6: COLOR 1:PRINT "CHIEF ENGINEER SCOTT REPORTS THE"
    PRINT "ENGINES WONT TAKE WARP ";NAV_WARP_FACTOR;"!";: BACKGROUND 0 : RETURN ST_COMMAND
    END IF
    REM KLINGONS MOVE/FIRE ON MOVING STARSHIP . . .
    KlingonsMove: FOR I=1 TO K3 : IF K(I,3)=0 THEN CONTINUE FOR
    A$=EMPTY_TOKEN$ : TOKEN_X=K(I,1) : TOKEN_Y=K(I,2) : PlaceToken() : FindEmpty()
    K(I,1)=TOKEN_X : K(I,2)=TOKEN_Y : A$=KLINGON_TOKEN$ : PlaceToken()
    NEXT I : KlingonsFire()
    IF SHIPDEAD THEN RETURN ST_DEAD
    D1=0 : D6=NAV_WARP_FACTOR : IF NAV_WARP_FACTOR>=1 THEN D6=1
    FOR I=1 TO 8 : IF DEVICE_DAMAGE(I)>=0 THEN CONTINUE FOR
    DEVICE_DAMAGE(I)=DEVICE_DAMAGE(I)+D6 : IF DEVICE_DAMAGE(I)>-.1AND DEVICE_DAMAGE(I)<0THEN DEVICE_DAMAGE(I)=-.1 : CONTINUE FOR
    IF DEVICE_DAMAGE(I)<0 THEN CONTINUE FOR
    IF D1<>1 THEN D1=1 : PRINT : PRINT "DAMAGE CONTROL REPORT :   "
    DEVICE_INDEX=I : DeviceName() : PRINT G2$;" REPAIR COMPLETED"
    NEXT I
    IF RND(1)<=.2 THEN
    DEVICE_INDEX=FNR(1)
    IF RND(1)<.6 THEN
    DEVICE_DAMAGE(DEVICE_INDEX)=DEVICE_DAMAGE(DEVICE_INDEX)-(RND(1)*5+1) : PRINT : PRINT "DAMAGE CONTROL REPORTS:"
    DeviceName() : PRINT G2$;" DAMAGED"
    ELSE
    DEVICE_DAMAGE(DEVICE_INDEX)=DEVICE_DAMAGE(DEVICE_INDEX)+RND(1)*3+1 : PRINT : PRINT "DAMAGE CONTROL REPORTS:"
    DeviceName() : PRINT G2$;" PARTLY REPAIRED"
    END IF
    END IF
    REM BEGIN MOVING STARSHIP
    A$=EMPTY_TOKEN$ : TOKEN_X=INT(SECTOR_X) : TOKEN_Y=INT(SECTOR_Y) : PlaceToken()
    X1=COURSE_VEC(C1,1)+(COURSE_VEC(C1+1,1)-COURSE_VEC(C1,1))*(C1-INT(C1)) : X=SECTOR_X : Y=SECTOR_Y
    X2=COURSE_VEC(C1,2)+(COURSE_VEC(C1+1,2)-COURSE_VEC(C1,2))*(C1-INT(C1)) : Q4=QUADRANT_X : Q5=QUADRANT_Y
    MoveInterrupted=0 : CrossedQuadrant=0
    FOR I=1 TO N : SECTOR_X=SECTOR_X+X1 : SECTOR_Y=SECTOR_Y+X2
        IF SECTOR_X<1 OR SECTOR_X>=9 OR SECTOR_Y<1 OR SECTOR_Y>=9 THEN CrossedQuadrant=1 : EXIT FOR
        S8=INT(SECTOR_X)*24+INT(SECTOR_Y)*3-26 : IF MID$(QUADRANT_BUFFER$,S8,2)="  "THEN CONTINUE FOR
        SECTOR_X=INT(SECTOR_X-X1) : SECTOR_Y=INT(SECTOR_Y-X2) : PRINT : PRINT "WARP ENGINES SHUT DOWN AT ";
        PRINT "SECTOR ";SECTOR_X;",";SECTOR_Y
        PRINT "DUE TO BAD NAVIGATION"
        SRSFLAG=1
        MoveInterrupted=1
        EXIT FOR
    NEXT I
    IF CrossedQuadrant=1 THEN
    X=8*QUADRANT_X+X+N*X1 : Y=8*QUADRANT_Y+Y+N*X2 : QUADRANT_X=INT(X/8) : QUADRANT_Y=INT(Y/8) : SECTOR_X=INT(X-QUADRANT_X*8)
    SECTOR_Y=INT(Y-QUADRANT_Y*8) : IF SECTOR_X=0 THEN QUADRANT_X=QUADRANT_X-1 : SECTOR_X=8
    IF SECTOR_Y=0 THEN QUADRANT_Y=QUADRANT_Y-1 : SECTOR_Y=8
    X5=0 : IF QUADRANT_X<1 THEN X5=1 : QUADRANT_X=1 : SECTOR_X=1
    IF QUADRANT_X>8 THEN X5=1 : QUADRANT_X=8 : SECTOR_X=8
    IF QUADRANT_Y<1 THEN X5=1 : QUADRANT_Y=1 : SECTOR_Y=1
    IF QUADRANT_Y>8 THEN X5=1 : QUADRANT_Y=8 : SECTOR_Y=8
    IF X5<>0 THEN
    PRINT : BACKGROUND 6: COLOR 1: PRINT "LT. UHURA REPORTS MESSAGE FROM STARFLEET";
    PRINT " COMMAND:{13}PERMISSION TO ATTEMPT CROSSING OF GALACTIC PERIMETER IS HEREBY{13}{RED}*DENIED*{WHITE}";
    PRINT " - SHUT DOWN YOUR ENGINES.{13}{13} CHIEF ENGINEER SCOTT REPORTS WARP";
    PRINT " ENGINES SHUT DOWN AT SECTOR ";SECTOR_X;",";SECTOR_Y;" OF QUADRANT ";QUADRANT_X;",";QUADRANT_Y;".";:
    BACKGROUND 0: PRINT
    SRSFLAG=1
    PRINT : Pause()
    IF STARDATE_CUR>STARDATE_START+MISSION_DAYS THEN RETURN ST_GAMEOVER
    END IF
    IF 8*QUADRANT_X+QUADRANT_Y=8*Q4+Q5 THEN 
    A$=ENTERPRISE_TOKEN$ : TOKEN_X=INT(SECTOR_X) : TOKEN_Y=INT(SECTOR_Y) : PlaceToken() : ManeuverEnergy() : T8=1
    IF NAV_WARP_FACTOR<1 THEN T8=.1*INT(10*NAV_WARP_FACTOR)
    STARDATE_CUR=STARDATE_CUR+T8 : IF STARDATE_CUR>STARDATE_START+MISSION_DAYS THEN RETURN ST_GAMEOVER
    RETURN ShortRangeScan()
    END IF
    STARDATE_CUR=STARDATE_CUR+1 : ManeuverEnergy() : RETURN ST_NEWQUAD
    END IF
    IF MoveInterrupted=0 THEN 
      SECTOR_X=INT(SECTOR_X)
      SECTOR_Y=INT(SECTOR_Y)
    END IF
    A$=ENTERPRISE_TOKEN$ : TOKEN_X=INT(SECTOR_X) : TOKEN_Y=INT(SECTOR_Y) : PlaceToken() : ManeuverEnergy() : T8=1
    IF NAV_WARP_FACTOR<1 THEN T8=.1*INT(10*NAV_WARP_FACTOR)
    STARDATE_CUR=STARDATE_CUR+T8 : IF STARDATE_CUR>STARDATE_START+MISSION_DAYS THEN RETURN ST_GAMEOVER

    REM SEE IF DOCKED, THEN GET COMMAND
    RETURN ShortRangeScan()
END FUNCTION




REM MANEUVER ENERGY S/R **
FUNCTION ManeuverEnergy()
    SHIP_ENERGY=SHIP_ENERGY-N-10
    IF SHIP_ENERGY>=0 THEN RETURN
    PRINT : PRINT "SHIELD CONTROL SUPPLIES ENERGY TO"
    PRINT "COMPLETE THE MANOEUVRE."
    SHIELD_UNITS=SHIELD_UNITS+SHIP_ENERGY
    SHIP_ENERGY=0
    IF SHIELD_UNITS<=0 THEN SHIELD_UNITS=0
    RETURN
END FUNCTION




REM ** ===== LONG RANGE SCAN ===== **
FUNCTION Lrs()
    K1=0
    IF DEVICE_DAMAGE(3)<0 THEN 
      PRINT
      PRINT "LONG RANGE SENSORS ARE INOPERABLE"
      SLSFLAG=0
      RETURN ST_COMMAND
    END IF
    PRINT : PRINT "{13}{LIGHTBLUE}LONG RANGE SCAN FOR QUADRANT{WHITE} ";QUADRANT_X;",";QUADRANT_Y
    PRINT : O1$=" ┌─────┬─────┬─────┐" : PRINT "{13}{GREEN}";O1$;
    O2$=" ├─────┼─────┼─────┤":O3$=" {173}─────{177}─────{177}─────{189}" 
    PRINT "         ";ECOL$;"#";DCOL$;"#";HCOL$;"#";FCOL$
    FOR I=QUADRANT_X-1 TO QUADRANT_X+1 : N(1)=-1 : N(2)=-2 : N(3)=-3 : FOR J=QUADRANT_Y-1 TO QUADRANT_Y+1
    IF I>0 AND I<9 AND J>0 AND J<9 THEN N(J-QUADRANT_Y+2)=G(I,J) : Z(I,J)=G(I,J)
    NEXT J : FOR L=1 TO 3
    IF K1=2 AND L=3 THEN PRINT "";
    PRINT " {221}";
    PRINT " ";
    IF N(L)<0 THEN 
      PRINT "▒▒▒";
      CONTINUE FOR
    END IF
    G1$=RIGHT$(STR$(N(L)+1000),3)
    G2$=ECOL$+MID$(G1$,1,1) : PRINT G2$;
    G2$=DCOL$+MID$(G1$,2,1) : PRINT G2$;
    G2$=HCOL$+MID$(G1$,3,1) : PRINT G2$;FCOL$;
    NEXT L : PRINT " {221}"; : K1=K1+1
    IF K1=1 THEN PRINT "        . . ."
    IF K1=3 THEN PRINT "      .   .   ."
    IF K1=5 THEN PRINT "    .           ."
    K1=K1+1 : IF K1<6 THEN PRINT O2$;
    IF K1=6 THEN PRINT O3$;
    IF K1=2 THEN PRINT "       .  .  ."
    IF K1=4 THEN PRINT "     .  {CYAN}BASES{GREEN}";
    IF K1=4 THEN PRINT "  ."
    IF K1=6 THEN PRINT "  {PINK}KLINGONS{WHITE}    {YELLOW}STARS{WHITE}"
    NEXT I : K1=0 : IF SLSFLAG=1 THEN SLSFLAG=0
    RETURN ST_COMMAND
END FUNCTION


REM ** ===== PHASER CONTROL ===== **
FUNCTION Phasers()
    IF DEVICE_DAMAGE(4)<0 THEN PRINT : PRINT "PHASERS INOPERATIVE" : RETURN ST_COMMAND
    IF K3<=0 THEN NoEnemyMsg() : RETURN ST_COMMAND
    IF DEVICE_DAMAGE(8)<0 THEN PRINT : PRINT "COMPUTER FAILURE HAMPERS ACCURACY"
    PRINT : PRINT "PHASERS LOCKED ON TARGET!  "
    DO
    PRINT : PRINT "ENERGY AVAILABLE = ";SHIP_ENERGY;" UNITS"
    LX=5 : PRINT "NUMBER OF UNITS TO FIRE :  "; : GetInput()
    X=VAL(LII$) : IF X<=0 THEN RETURN ST_COMMAND
    LOOP UNTIL SHIP_ENERGY-X>=0
    SHIP_ENERGY=SHIP_ENERGY-X : IF DEVICE_DAMAGE(7)<0 THEN X=X*RND(1)
    H1=INT(X/K3) : FOR I=1 TO 3 : IF K(I,3)<=0 THEN CONTINUE FOR
    H=INT((H1/FND(0))*(RND(1)+2))
    IF H<=.15*K(I,3) THEN 
    PRINT : PRINT " SENSORS SHOW NO DAMAGE TO ENEMY"
    PRINT " AT ";K(I,1);",";K(I,2)
    CONTINUE FOR
    END IF
    K(I,3)=K(I,3)-H : PRINT
    PRINT H;" UNIT HIT KLINGON AT ";K(I,1);",";K(I,2)
    IF K(I,3)>0 THEN 
    PRINT " (SENSORS SHOW ";INT(K(I,3));" UNITS REMAINING)"
    CONTINUE FOR
    END IF
    PRINT " *** KLINGON DESTROYED ***"
    K3=K3-1 : KLINGON_COUNT=KLINGON_COUNT-1 : TOKEN_X=K(I,1) : TOKEN_Y=K(I,2) : A$=EMPTY_TOKEN$ : PlaceToken()
    K(I,3)=0 : G(QUADRANT_X,QUADRANT_Y)=G(QUADRANT_X,QUADRANT_Y)-100 : Z(QUADRANT_X,QUADRANT_Y)=G(QUADRANT_X,QUADRANT_Y) : IF KLINGON_COUNT<=0 THEN RETURN ST_VICTORY
    NEXT I
    IF K3>0 THEN PRINT : Pause()
    KlingonsFire()
    IF SHIPDEAD THEN RETURN ST_DEAD
    RETURN ST_COMMAND
END FUNCTION


REM ** ===== PHOTON TORPEDO ===== **
FUNCTION Torpedo()
    IF TORPEDO_COUNT<=0 THEN PRINT : PRINT "ALL PHOTON TORPEDOES EXPENDED" : RETURN ST_COMMAND
    IF DEVICE_DAMAGE(5)<0 THEN PRINT : PRINT "PHOTON TUBES ARE NOT OPERATIONAL" : RETURN ST_COMMAND
    DO
    ShowDirections() : REM ** DIRECTION HELPER **
    PRINT : LX=5 : PRINT "PHOTON TORPEDO COURSE (1-9) :  "; : GetInput()
    C1=VAL(LII$) : IF C1=9 THEN C1=1
    IF C1<1 OR C1>=9 THEN
    PRINT : BACKGROUND 6: COLOR 1: PRINT "ENSIGN CHEKOV REPORTS, INCORRECT"
    PRINT "COURSE DATA, SIR!";:BACKGROUND 0: PRINT : RETURN ST_COMMAND
    END IF
    X1=COURSE_VEC(C1,1)+(COURSE_VEC(C1+1,1)-COURSE_VEC(C1,1))*(C1-INT(C1)) : SHIP_ENERGY=SHIP_ENERGY-2 : TORPEDO_COUNT=TORPEDO_COUNT-1
    X2=COURSE_VEC(C1,2)+(COURSE_VEC(C1+1,2)-COURSE_VEC(C1,2))*(C1-INT(C1)) : X=SECTOR_X : Y=SECTOR_Y
    PRINT : PRINT "TORPEDO TRACKING:"
    RetryCourse=0
    DO
    X=X+X1 : Y=Y+X2 : X3=INT(X+.5) : Y3=INT(Y+.5)
    IF X3<1 OR X3>8 OR Y3<1 OR Y3>8 THEN
    PRINT " ** TORPEDO MISSED **"
    IF K3<>0 THEN PRINT : Pause()
    KlingonsFire()
    IF SHIPDEAD THEN RETURN ST_DEAD
    RETURN ST_COMMAND
    END IF
    PRINT " ";X3;",";Y3 : A$=EMPTY_TOKEN$ : TOKEN_X=X : TOKEN_Y=Y : CheckSector()
    IF Z3<>0 THEN CONTINUE DO

    A$=KLINGON_TOKEN$ : TOKEN_X=X : TOKEN_Y=Y : CheckSector()
    IF Z3<>0 THEN
    PRINT " *** KLINGON DESTROYED ***"
    K3=K3-1 : IF K3>0 THEN PRINT : Pause()
    KLINGON_COUNT=KLINGON_COUNT-1 : IF KLINGON_COUNT<=0 THEN RETURN ST_VICTORY
    HitIdx=3
    FOR I=1 TO 3
    IF X3=K(I,1) AND Y3=K(I,2) THEN HitIdx=I : EXIT FOR
    NEXT I
    K(HitIdx,3)=0
    TOKEN_X=X : TOKEN_Y=Y : A$=EMPTY_TOKEN$ : PlaceToken()
    G(QUADRANT_X,QUADRANT_Y)=K3*100+B3*10+S3 : Z(QUADRANT_X,QUADRANT_Y)=G(QUADRANT_X,QUADRANT_Y) : KlingonsFire()
    IF SHIPDEAD THEN RETURN ST_DEAD
    RETURN ST_COMMAND
    END IF

    A$=STAR_TOKEN$ : TOKEN_X=X : TOKEN_Y=Y : CheckSector()
    IF Z3<>0 THEN
    PRINT " ** STAR AT";X3;",";Y3;"ABSORBED TORPEDO **"
    IF K3<>0 THEN PRINT : Pause()
    KlingonsFire()
    IF SHIPDEAD THEN RETURN ST_DEAD
    RETURN ST_COMMAND
    END IF

    A$=STARBASE_TOKEN$ : TOKEN_X=X : TOKEN_Y=Y : CheckSector()
    IF Z3=0 THEN
    RetryCourse=1
    EXIT DO
    END IF
    PRINT " *** STARBASE DESTROYED ***"
    PRINT : Pause()
    B3=B3-1 : STARBASE_COUNT=STARBASE_COUNT-1
    IF STARBASE_COUNT<=0 AND KLINGON_COUNT<=STARDATE_CUR-STARDATE_START-MISSION_DAYS THEN
    PRINT : BACKGROUND 6: COLOR 1: PRINT "THAT DOES IT, CAPTAIN!!  YOU ARE HEREBY"
    PRINT "RELIEVED OF COMMAND AND SENTENCED TO 99"
    PRINT "STARDATES AT HARD LABOUR ON CYGNUS 12!!";:BACKGROUND 0
    RETURN ST_MISSIONEND
    END IF
    PRINT : PRINT "STARFLEET COMMAND REVIEWING YOUR RECORD"
    PRINT "TO CONSIDER COURT MARTIAL!" : D0=0
    TOKEN_X=X : TOKEN_Y=Y : A$=EMPTY_TOKEN$ : PlaceToken()
    G(QUADRANT_X,QUADRANT_Y)=K3*100+B3*10+S3 : Z(QUADRANT_X,QUADRANT_Y)=G(QUADRANT_X,QUADRANT_Y) : KlingonsFire()
    IF SHIPDEAD THEN RETURN ST_DEAD
    RETURN ST_COMMAND
    LOOP
    IF RetryCourse=1 THEN CONTINUE DO
    LOOP
END FUNCTION


REM ** ===== SHIELD CONTROL ===== **
FUNCTION Shields()
    IF DEVICE_DAMAGE(7)<0 THEN PRINT : PRINT "SHIELD CONTROL INOPERABLE" : RETURN ST_COMMAND
    PRINT : PRINT "ENERGY AVAILABLE = ";SHIP_ENERGY+SHIELD_UNITS
    LX=5 : PRINT "NUMBER OF UNITS TO SHIELDS :  "; : GetInput()
    X=VAL(LII$)
    IF X<0 OR SHIELD_UNITS=X THEN PRINT "<SHIELDS UNCHANGED>" : RETURN ST_COMMAND
    IF X>SHIP_ENERGY+SHIELD_UNITS THEN
    PRINT :  BACKGROUND 6: COLOR 1: PRINT "SHIELD CONTROL REPORTS THIS IS NOT THE"
    PRINT "FEDERATION TREASURY."
    PRINT "<SHIELDS UNCHANGED>";:BACKGROUND 0: PRINT : RETURN ST_COMMAND
    END IF
    SHIP_ENERGY=SHIP_ENERGY+SHIELD_UNITS-X : SHIELD_UNITS=X : PRINT :BACKGROUND 6: COLOR 1: PRINT "DEFLECTOR CONTROL ROOM REPORT:"
    PRINT "SHIELDS NOW AT ";INT(SHIELD_UNITS);" UNITS PER"
    PRINT "YOUR COMMAND.";:BACKGROUND 0: PRINT : RETURN ST_COMMAND
END FUNCTION


REM ** ===== DAMAGE CONTROL ===== **
FUNCTION Damage()
    IF DEVICE_DAMAGE(6)<0 THEN
    PRINT : PRINT "DAMAGE CONTROL REPORT NOT AVAILABLE"
    IF D0=0 THEN RETURN ST_COMMAND
    END IF
    DO
    IF DEVICE_DAMAGE(6)<0 AND D0<>0 THEN
    D3=0 : FOR I=1 TO 8 : IF DEVICE_DAMAGE(I)<0 THEN D3=D3+.1
    NEXT I : IF D3=0 THEN RETURN ST_COMMAND
    D3=D3+D4 : IF D3>=1 THEN D3=.9
    PRINT : PRINT "TECHNICIANS STANDING BY TO EFFECT"
    PRINT "REPAIRS TO YOUR SHIP;"
    PRINT "ESTIMATED TIME TO REPAIR: "
    PRINT .01*INT(100*D3);" STARDATES"
    LX=1 : PRINT : PRINT "AUTHORISE THE REPAIR ORDER (Y/N)? "; : GetInput()
    A$=LII$
    IF A$<>"Y" THEN RETURN ST_COMMAND
    FOR I=1 TO 8 : IF DEVICE_DAMAGE(I)<0 THEN DEVICE_DAMAGE(I)=0
    NEXT I : STARDATE_CUR=STARDATE_CUR+D3+.1
    END IF
    PRINT : PRINT " SYSTEM              STATE OF REPAIR"
    PRINT      " ------------------- -----------------"
    FOR DEVICE_INDEX=1 TO 8
    DeviceName() : PRINT " ";G2$;LEFT$(SPACE_PAD$,20-LEN(G2$));
    D2=INT(DEVICE_DAMAGE(DEVICE_INDEX)*100)*.01
    IF D2<0 THEN PRINT CCOL$;"DAMAGED     ";D2;FCOL$
    IF D2>0 THEN PRINT "OPERATIONAL ";D2
    IF D2=0 THEN PRINT "OPERATIONAL ";D2
    NEXT DEVICE_INDEX
    IF D0=0 THEN EXIT DO
    LOOP
    RETURN ST_COMMAND
END FUNCTION


REM ** ===== KLINGONS SHOOT BACK (SETS SHIPDEAD IF SHIELDS FAIL) ===== **
FUNCTION KlingonsFire()
    SHIPDEAD=0
    IF K3<=0 THEN RETURN
    IF D0<>0 THEN PRINT : PRINT "STARBASE SHIELDS PROTECT THE ENTERPRISE"
    IF D0<>0 THEN RETURN
    FOR I=1 TO 3 : IF K(I,3)<=0 THEN CONTINUE FOR
    H=INT((K(I,3)/FND(1))*(2+RND(1))) : SHIELD_UNITS=SHIELD_UNITS-H : K(I,3)=K(I,3)/(3+RND(0))
    PRINT : PRINT H;" UNIT HIT ENTERPRISE FROM ";K(I,1);",";K(I,2)
    IF SHIELD_UNITS<=0 THEN SHIPDEAD=1 : RETURN
    PRINT " <SHIELDS DOWN TO ";SHIELD_UNITS;" UNITS>" : IF H<20 THEN CONTINUE FOR
    IF RND(1)>.6 OR H/SHIELD_UNITS<=.02 THEN CONTINUE FOR
    DEVICE_INDEX=FNR(1) : DEVICE_DAMAGE(DEVICE_INDEX)=DEVICE_DAMAGE(DEVICE_INDEX)-H/SHIELD_UNITS-.5*RND(1) : DeviceName()
    PRINT : BACKGROUND 6: COLOR 1: PRINT "DAMAGE CONTROL REPORTS :  "
    PRINT G2$;" DAMAGED BY THE HIT";:BACKGROUND 0: PRINT
    NEXT I
    ATAKFLAG=1
    RETURN
END FUNCTION


REM ** ===== END-OF-GAME STATES ===== **
FUNCTION ShowGameOver()
    PRINT : PRINT "IT IS STARDATE ";STARDATE_CUR
    RETURN ST_MISSIONEND
END FUNCTION


FUNCTION ShipDestroyed()
    PRINT : Pause()
    PRINT : PRINT "{RED}THE ENTERPRISE HAS BEEN DESTROYED.{WHITE}"
    PRINT CHR$(13);"THE FEDERATION WILL BE CONQUERED"
    RETURN ST_GAMEOVER
END FUNCTION


FUNCTION ShowMissionEnd()
    PRINT : PRINT "THERE WERE ";KLINGON_COUNT;" KLINGON BATTLE CRUISERS"
    PRINT "LEFT AT THE END OF YOUR MISSION."
    RETURN ST_PLAYAGAIN
END FUNCTION


FUNCTION AskPlayAgain()
    IF STARBASE_COUNT=0 THEN RETURN ST_QUIT
    PRINT : PRINT "THE FEDERATION IS IN NEED OF A NEW"
    PRINT "STARSHIP COMMANDER FOR ANOTHER MISSION."
    PRINT : PRINT "... IF THERE IS A VOLUNTEER,"
    LX=3 : PRINT "STEP FORWARD AND ENTER AYE :  "; : GetInput()
    A$=LII$ : IF A$="AYE" THEN RETURN ST_NEWGAME
    RETURN ST_QUIT
END FUNCTION


FUNCTION ShowVictory()
    PRINT : Pause()
    PRINT : PRINT "CONGRATULATIONS, CAPTAIN! THE LAST"
    PRINT "KLINGON BATTLE CRUISER MENACING THE"
    PRINT "FEDERATION HAS BEEN DESTROYED."
    PRINT : PRINT "YOUR EFFICIENCY RATING IS";
    PRINT INT(1000*(K7/(STARDATE_CUR-STARDATE_START))^2)
    RETURN ST_PLAYAGAIN
END FUNCTION


REM ** ===== SHORT RANGE SCAN & SUMMARY (SLS CHAINS INTO LRS) ===== **
FUNCTION ShortRangeScan()
    IF ATAKFLAG=1 THEN
      PRINT
      Pause()
    END IF
    IF DEVICE_DAMAGE(2)<0 THEN
      PRINT
      PRINT "*** SHORT RANGE SENSORS ARE OUT ***"
      IF SLSFLAG=1 THEN RETURN Lrs()
      RETURN ST_COMMAND
    END IF
    IF SRSFLAG=0 THEN
      PRINT
      PRINT "{LIGHTBLUE}SHORT RANGE SCAN + SUMMARY DATA{WHITE}"
    END IF
    SRSFLAG=0
    ATAKFLAG=0
    Docked=0
    FOR I=SECTOR_X-1 TO SECTOR_X+1
    FOR J=SECTOR_Y-1 TO SECTOR_Y+1
      IF INT(I+.5)<1 OR INT(I+.5)>8 OR INT(J+.5)<1 OR INT(J+.5)>8 THEN CONTINUE FOR
      A$=STARBASE_TOKEN$
      TOKEN_X=I
      TOKEN_Y=J
      CheckSector()
      IF Z3=1 THEN
        Docked=1
        EXIT FOR
      END IF
    NEXT J
    IF Docked=1 THEN
      EXIT FOR
    END IF
    NEXT I
    IF Docked=1 THEN
      D0=1
      C$="DOCKED"
      SHIP_ENERGY=ENERGY_MAX
      TORPEDO_COUNT=TORPEDO_MAX
      PRINT
      PRINT "SHIELDS DROPPED FOR DOCKING PURPOSES"
      SHIELD_UNITS=0
    ELSE
      D0=0
      IF K3>0 THEN C$="RED"
      IF K3=0 THEN
        C$="GREEN"
        IF SHIP_ENERGY<ENERGY_MAX*.1 THEN C$="AMBER"
      END IF
    END IF
    IF K3>0 THEN
      PRINT
      PRINT CCOL$;"COMBAT AREA  ";
      PRINT "** CONDITION RED **";FCOL$
    END IF
    LOW$=" LOW!"
    PRINT
    PRINT "   {YELLOW}1 2 3 4 5 6 7 8"
    PRINT "  {GREEN}{176}─{178}─{178}─{178}─{178}─{178}─{178}─{178}─┐{WHITE} {LIGHTBLUE}STARDATE{YELLOW}  ";INT(STARDATE_CUR*10)*.1
    FOR I=1 TO 8
      I$=RIGHT$(STR$(I),1)
      PRINT "{YELLOW}";I$;" {GREEN}{125}{WHITE}"; : REM BORDER
      J1=(I-1)*24+1
      J2=(I-1)*24+22
      FOR J = J1 TO J2 STEP 3
        Z3$=MID$(QUADRANT_BUFFER$,J,3)
        IF Z3$="   " THEN PRINT " ";
        IF Z3$<>"   " THEN PRINT LEFT$(Z3$,1);
        PRINT "{GREEN}{125}{WHITE}";
      NEXT J
      SELECT CASE I
      CASE 1
        PRINT " {LIGHTBLUE}DAYS LEFT{YELLOW} ";.1*INT((STARDATE_START+MISSION_DAYS-STARDATE_CUR)*10);
      CASE 2
        PRINT " {LIGHTBLUE}CONDITION{YELLOW} "; : PRINT C$;
      CASE 3
        PRINT " {LIGHTBLUE}QUADRANT  {YELLOW}";QUADRANT_X;",";QUADRANT_Y;
      CASE 4
        PRINT " {LIGHTBLUE}SECTOR    {YELLOW}";SECTOR_X;",";SECTOR_Y;
      CASE 5
        PRINT " {LIGHTBLUE}TORPEDOES {YELLOW}";INT(TORPEDO_COUNT);
      CASE 6
        PRINT " {LIGHTBLUE}ENERGY    {YELLOW}";INT(SHIP_ENERGY+SHIELD_UNITS);
      CASE 7
        PRINT " {LIGHTBLUE}SHIELDS   {YELLOW}";INT(SHIELD_UNITS);
        IF SHIELD_UNITS<201 AND K3>0 THEN PRINT LOW$;
      CASE 8
        PRINT " {LIGHTBLUE}KLINGONS  {YELLOW}";INT(KLINGON_COUNT);
      END SELECT
      PRINT
    NEXT I
    PRINT "  {GREEN}{173}─{177}─{177}─{177}─{177}─{177}─{177}─{177}─{189}{WHITE}";
    MW=SHIP_ENERGY/8
    MW=MW*10
    MW=INT(MW)
    MW=MW/10
    IF MW>8 THEN MW=8
    IF DEVICE_DAMAGE(1)<0 AND MW>0.2 THEN MW=0.2
    PRINT " {LIGHTBLUE}MAX WARP{YELLOW}  ";MW
    IF SLSFLAG=1 THEN RETURN Lrs()
    RETURN ST_COMMAND
END FUNCTION


REM ** ===== LIBRARY COMPUTER ===== **
FUNCTION Computer()
    IF DEVICE_DAMAGE(8)<0 THEN PRINT : PRINT "SHIPS COMPUTER DISABLED" : RETURN ST_COMMAND
    PRINT : PRINT "FUNCTIONS AVAILABLE FROM COMPUTER:" : PRINT
    PRINT " 0 - CUMULATIVE GALACTIC RECORD"
    PRINT " 1 - STATUS & DAMAGE REPORT"
    PRINT " 2 - PHOTON TORPEDO TARGETING DATA"
    PRINT " 3 - STARBASE NAV DATA"
    PRINT " 4 - DIRECTION/DISTANCE CALCULATOR"
    PRINT " 5 - GALAXY REGION NAME MAP"
    PRINT : LX=1 : PRINT CHR$(13);"COMPUTER ACTIVE & AWAITING COMMAND :  ";
    IF COMFLAG=1 THEN
      PRINT "0"
      A=0
      A1=A
    ELSE
      GetInput()
      A=VAL(LII$) : A1=A : IF A<0 OR A>5 THEN RETURN ST_COMMAND
      IF LII$="" THEN RETURN ST_COMMAND
    END IF
    SELECT CASE A
    CASE 0
      H8=1 : G5=0 : A=0 : A1=0
      RETURN ComputerGalacticRecord()
    CASE 1
      RETURN ComputerStatusReport()
    CASE 2
      RETURN ComputerNavCalcKlingon()
    CASE 3
      RETURN ComputerBaseNav()
    CASE 4
      RETURN ComputerCalculator()
    CASE 5
      RETURN ComputerGalaxyMap()
    END SELECT
    RETURN ST_COMMAND
END FUNCTION


FUNCTION ComputerGalacticRecord()
    REM GALFLAG marks the highlighted current quadrant separator slot.
    GALFLAG=0
    IF G5=0 THEN
      PRINT
      PRINT "{CLR}{REVERSE ON}COMPUTER RECORD OF GALAXY FOR "
      PRINT "QUADRANT ";QUADRANT_X;",";QUADRANT_Y
      PRINT "{REVERSE OFF}"
      PRINT CHR$(13);
      PRINT "   ";
    END IF
    FOR J=1 TO 8
      J$=STR$(J)
      J$=RIGHT$(J$,1)
      IF A1=5 THEN RomanNumeral() : CONTINUE FOR
      IF J=QUADRANT_Y THEN PRINT " {WHITE}";J$;"{GREEN}  ";
      IF J<>QUADRANT_Y THEN PRINT " {GREEN}";J;"{GREEN}  ";
    NEXT J
    PRINT
    O1$="  ┌───┬───┬───┬───┬───┬───┬───┬───┐"
    O2$="  ├───┼───┼───┼───┼───┼───┼───┼───┤"
    PRINT O1$
    FOR I=1 TO 8
      I$=STR$(I)
      I$=RIGHT$(I$,1)
      IF I=QUADRANT_X THEN PRINT " ";I$;"";
      RowIsRegion=0
      IF A1=5 AND I=QUADRANT_X THEN RowIsRegion=1
      IF I<>QUADRANT_X THEN PRINT " ";I$; : IF H8=0 THEN RowIsRegion=1
      IF RowIsRegion=0 THEN
      FOR J=1 TO 8
        IF I=QUADRANT_X AND J=QUADRANT_Y THEN PRINT "{221}"; : GALFLAG=1
        IF NOT (I=QUADRANT_X AND (J=QUADRANT_Y OR J-1=QUADRANT_Y)) THEN PRINT "{221}";
        IF Z(I,J)=0 THEN PRINT "   "; : CONTINUE FOR
        G1$=RIGHT$(STR$(Z(I,J)+1000),3)
        G2$=ECOL$+MID$(G1$,1,1) : PRINT G2$;
        G2$=DCOL$+MID$(G1$,2,1) : PRINT G2$;
        G2$=HCOL$+MID$(G1$,3,1) : PRINT G2$;FCOL$;
        IF GALFLAG=1 THEN PRINT "{221}"; : GALFLAG=0
      NEXT J
      END IF
      IF RowIsRegion=1 THEN
        J=9
        Z4=I : Z5=1 : QuadrantName() : J0=INT(11-.5*LEN(G2$))
        PRINT "{221}";
        PRINT TAB(J0);G2$;
        PRINT TAB(18);"{221}";
        Z5=5 : QuadrantName() : J0=INT(27-.5*LEN(G2$))
        PRINT TAB(J0);G2$; : PRINT TAB(34);"{221}";
      END IF
      IF A=0 AND J=9 AND QUADRANT_X=I AND QUADRANT_Y=8 THEN PRINT
      IF NOT (A=0 AND J=9 AND QUADRANT_X=I AND QUADRANT_Y=8) THEN IF A=0 THEN PRINT "{221}"
      IF A=5 THEN PRINT
      IF I<8 THEN PRINT O2$
    NEXT I
    PRINT "  {173}{45}{178}─{177}───{177}───{177}───{177}───{177}───{177}───{177}───{189}"
    A1=0
    RETURN ST_COMMAND
END FUNCTION


FUNCTION ComputerGalaxyMap()
    H8=0
    G5=1
    A=5
    A1=5
    PRINT : PRINT "{CLR}{REVERSE ON}THE GALAXY:{REVERSE OFF}" : PRINT : PRINT "   ";
    RETURN ComputerGalacticRecord()
END FUNCTION


FUNCTION ComputerStatusReport()
    PRINT : PRINT "{CLR}{REVERSE ON}STATUS REPORT:{REVERSE OFF}";CHR$(13) : X$="" : IF KLINGON_COUNT>1 THEN X$="S"
    PRINT : PRINT " KLINGONS LEFT :";KLINGON_COUNT
    PRINT " ENERGY        :";INT(SHIP_ENERGY+SHIELD_UNITS)
    PRINT " TORPEDOES     :";INT(TORPEDO_COUNT)
    PRINT : PRINT "{13} MISSION MUST BE COMPLETED IN ";.1*INT((STARDATE_START+MISSION_DAYS-STARDATE_CUR)*10)
    PRINT " STARDATES"
    X$="S" : IF STARBASE_COUNT<2THEN X$=""
    IF STARBASE_COUNT<1 THEN
      PRINT : PRINT "{13}YOUR STUPIDITY HAS LEFT YOU ON YOUR OWN"
      PRINT "IN THE GALAXY -- YOU HAVE NO STARBASES"
      PRINT "LEFT!" : RETURN Damage()
    END IF
    PRINT : PRINT "{13} THE FEDERATION IS MAINTAINING ";STARBASE_COUNT
    PRINT " STARBASE";X$;" IN THE GALAXY"; CHR$(13)
    RETURN Damage()
END FUNCTION


FUNCTION ComputerNavCalcKlingon()
    IF K3<=0 THEN NoEnemyMsg() : RETURN ST_COMMAND
    X$="" : IF K3>1THEN X$="S"
    PRINT : PRINT "FROM ENTERPRISE TO KLINGON SHIP";
    PRINT X$
    H8=0 : A1=2
    FOR I=1 TO 3
    IF K(I,3)<=0 THEN CONTINUE FOR
    CALC_TARGET_Y=K(I,1) : X=K(I,2)
    C1=SECTOR_X : A=SECTOR_Y : ComputerCalcCompute()
    NEXT I
    RETURN ST_COMMAND
END FUNCTION


FUNCTION ComputerCalculator()
    H8=1 : A1=4
    PRINT : PRINT "DIRECTION/DISTANCE CALCULATOR:"
    PRINT : PRINT "YOU ARE AT QUADRANT ";QUADRANT_X;",";QUADRANT_Y
    PRINT "             SECTOR ";SECTOR_X;",";SECTOR_Y
    PRINT : LX=4 : PRINT "ENTER INITIAL COORDINATES (Y) :  "; : GetInput()
    C1=VAL(LII$) : IF C1=0 THEN PRINT : PRINT "CALCULATION ABORTED!" : RETURN ST_COMMAND
    LX=4 : PRINT "ENTER INITIAL COORDINATES (X) :  "; : GetInput()
    A=VAL(LII$) : IF A=0 THEN PRINT : PRINT "CALCULATION ABORTED!" : RETURN ST_COMMAND
    PRINT : LX=4 : PRINT "ENTER FINAL COORDINATES   (Y) :  "; : GetInput()
    CALC_TARGET_Y=VAL(LII$) : IF CALC_TARGET_Y=0 THEN PRINT : PRINT "CALCULATION ABORTED!" : RETURN ST_COMMAND
    PRINT : LX=4 : PRINT "ENTER FINAL COORDINATES   (X) :  "; : GetInput()
    X=VAL(LII$) : IF X=0 THEN PRINT : PRINT "CALCULATION ABORTED!" : RETURN ST_COMMAND
    IF C1=CALC_TARGET_Y AND A=X THEN PRINT : PRINT "NO RESULTS POSSIBLE!" : RETURN ST_COMMAND
    RETURN ComputerCalcCompute()
END FUNCTION


FUNCTION ComputerBaseNav()
    H8=0 : A1=3
    IF B3<>0 THEN PRINT : PRINT "FROM ENTERPRISE TO STARBASE" : CALC_TARGET_Y=B4 : X=B5 : C1=SECTOR_X : A=SECTOR_Y : ComputerCalcCompute() : RETURN ST_COMMAND
    PRINT : PRINT "MR. SPOCK REPORTS, SENSORS SHOW NO"
    PRINT "STARBASES IN THIS QUADRANT." : RETURN ST_COMMAND
END FUNCTION


FUNCTION ComputerCalcCompute()
    X=X-A : A=C1-CALC_TARGET_Y
    IF X>=0 THEN
    IF A<0 THEN
    C1=7
    IF ABS(A)>=ABS(X) THEN
    PRINT : PRINT " DIRECTION =";
    D2=C1+(ABS(X)/ABS(A))
    ELSE
    PRINT : PRINT " DIRECTION =";
    D2=C1+(((ABS(X)-ABS(A))+ABS(X))/ABS(X))
    END IF
    ELSE
    IF X>0 OR A>0 THEN C1=1
    IF A=0 THEN C1=5
    IF ABS(A)<=ABS(X) THEN
    PRINT : PRINT " DIRECTION =";
    D2=C1+(ABS(A)/ABS(X))
    ELSE
    PRINT : PRINT " DIRECTION =";
    D2=C1+(((ABS(A)-ABS(X))+ABS(A))/ABS(A))
    END IF
    END IF
    ELSE
    IF A>0 THEN
    C1=3
    IF ABS(A)>=ABS(X) THEN
    PRINT : PRINT " DIRECTION =";
    D2=C1+(ABS(X)/ABS(A))
    ELSE
    PRINT : PRINT " DIRECTION =";
    D2=C1+(((ABS(X)-ABS(A))+ABS(X))/ABS(X))
    END IF
    ELSE
    C1=5
    IF ABS(A)<=ABS(X) THEN
    PRINT : PRINT " DIRECTION =";
    D2=C1+(ABS(A)/ABS(X))
    ELSE
    PRINT : PRINT " DIRECTION =";
    D2=C1+(((ABS(A)-ABS(X))+ABS(A))/ABS(A))
    END IF
    END IF
    END IF
    D2=D2*1000 : D2=D2+0.5 : D2=INT(D2) : D2=D2/1000
    PRINT D2
    PRINT " DISTANCE  =";
    D2=SQR(X^2+A^2)
    IF A1=3 OR A1=2 THEN D2=D2/10
    D2=D2*1000 : D2=D2+0.5 : D2=INT(D2) : D2=D2/1000
    PRINT D2
    RETURN ST_COMMAND
END FUNCTION


REM ** ===== SHARED MESSAGE: NO ENEMY IN QUADRANT ===== **
FUNCTION NoEnemyMsg()
    PRINT : BACKGROUND 6: COLOR 1: PRINT "SCIENCE OFFICER SPOCK REPORTS SENSORS"
    PRINT "SHOW NO ENEMY SHIPS IN THIS QUADRANT";:BACKGROUND 0: PRINT
    RETURN
END FUNCTION


REM FIND EMPTY PLACE IN QUADRANT (FOR THINGS)
FUNCTION FindEmpty()
    REM ** RETRY UNTIL CHECKSECTOR REPORTS THE SQUARE IS EMPTY (Z3<>0) **
    DO
    A$=EMPTY_TOKEN$
    RANDOM_X=FNR(1) : RANDOM_Y=FNR(1) : TOKEN_X=RANDOM_X : TOKEN_Y=RANDOM_Y
    CheckSector()
    LOOP UNTIL Z3<>0
    RETURN
END FUNCTION


REM INSERT IN STRING ARRAY FOR QUADRANT
FUNCTION PlaceToken()
    S8 = INT(TOKEN_Y-0.5) * 3 + INT(TOKEN_X-0.5) * 24 + 1
    IF LEN(A$)<>3 THEN PRINT "TOKEN LENGTH ERROR: ";A$;" LEN=";LEN(A$) : STOP
    IF S8=1THEN QUADRANT_BUFFER$=A$+RIGHT$(QUADRANT_BUFFER$,189) : RETURN
    IF S8=190THEN QUADRANT_BUFFER$=LEFT$(QUADRANT_BUFFER$,189)+A$ : RETURN
    QUADRANT_BUFFER$=LEFT$(QUADRANT_BUFFER$,S8-1)+A$+RIGHT$(QUADRANT_BUFFER$,190-S8) : RETURN
END FUNCTION


REM PRINTS DEVICE NAME -- SELECT CASE LOOKUP, NO GOTOS
FUNCTION DeviceName()
    SELECT CASE DEVICE_INDEX
    CASE 1
        G2$="WARP ENGINES"
    CASE 2
        G2$="SHORT RANGE SENSORS"
    CASE 3
        G2$="LONG RANGE SENSORS"
    CASE 4
        G2$="PHASER CONTROL"
    CASE 5
        G2$="PHOTON TUBES"
    CASE 6
        G2$="DAMAGE CONTROL"
    CASE 7
        G2$="SHIELD CONTROL"
    CASE 8
        G2$="LIBRARY-COMPUTER"
    END SELECT
    RETURN
END FUNCTION


REM STRING COMPARISON IN QUADRANT ARRAY
FUNCTION CheckSector()
    TOKEN_X=INT(TOKEN_X+.5) : TOKEN_Y=INT(TOKEN_Y+.5) : S8=(TOKEN_Y-1)*3+(TOKEN_X-1)*24+1 : Z3=0
    IF MID$(QUADRANT_BUFFER$,S8,3)<>A$ THEN RETURN
    Z3=1 : RETURN
END FUNCTION


REM QUADRANT NAME IN G2$ FROM Z4,Z5 (=Q1,Q2)
REM CALL WITH G5=1 TO GET REGION NAME ONLY
FUNCTION QuadrantName()
    REM ** REGIONS 1-4 OF EACH ROW USE THE FIRST NAME, 5-8 THE SECOND **
    SELECT CASE Z4
    CASE 1
        G2$="ANTARES" : IF Z5>4 THEN G2$="SIRIUS"
    CASE 2
        G2$="RIGEL" : IF Z5>4 THEN G2$="DENEB"
    CASE 3
        G2$="PROCYON" : IF Z5>4 THEN G2$="CAPELLA"
    CASE 4
        G2$="VEGA" : IF Z5>4 THEN G2$="BETELGEUSE"
    CASE 5
        G2$="CANOPUS" : IF Z5>4 THEN G2$="ALDEBARAN"
    CASE 6
        G2$="ALTAIR" : IF Z5>4 THEN G2$="REGULUS"
    CASE 7
        G2$="SAGITTARIUS" : IF Z5>4 THEN G2$="ARCTURUS"
    CASE 8
        G2$="POLLUX" : IF Z5>4 THEN G2$="SPICA"
    END SELECT
    IF G5=1 THEN RETURN
    SELECT CASE Z5
    CASE 1, 5
        G2$=G2$+" I"
    CASE 2, 6
        G2$=G2$+" II"
    CASE 3, 7
        G2$=G2$+" III"
    CASE 4, 8
        G2$=G2$+" IV"
    END SELECT
    RETURN
END FUNCTION


REM ** GET INPUT **
REM GET CHARACTERS UNTIL RETURN IS PRESSED
REM THEN RETURN 
FUNCTION GetInput()
    REM ** LX = MAX INPUT  LII$ = OUTPUT STRING **
    REM ** ACCEPTS A-Z/0-9/PUNCT + SPACE, CHR$(20)=BACKSPACE, ENTER ENDS **
    LII$=""
    DO 
        GET Y$
        Y$=UCASE$(Y$)
        IF Y$="" THEN CONTINUE DO
        IF ASC(Y$)=0 THEN Y$=CHR$(13)

        IF ASC(Y$)=13 AND LX=0 THEN
          PRINT "{CLR}"
          PRINT FCOL$
          RETURN
        END IF
        IF ASC(Y$)=13 THEN PRINT : PRINT FCOL$ : RETURN

        IF ASC(Y$)=20 AND LEN(LII$)<1 THEN CONTINUE DO
        IF Y$=CHR$(20) THEN Y$="" : LII$=LEFT$(LII$,(LEN(LII$)-1))

        IF ASC(Y$)<>32 AND (ASC(Y$)<46 OR ASC(Y$)>90) THEN CONTINUE DO

        IF LEN(LII$)<LX THEN PRINT Y$;
        IF LEN(LII$)<LX THEN LII$=LII$+Y$
    LOOP
END FUNCTION


FUNCTION Pause()
    REM ** PAUSE WITHOUT CR**
    IF CRSTART=1 THEN CR$="PRESS RETURN TO BEGIN"
    IF CRSTART=0 THEN CR$="PRESS RETURN TO CONTINUE"
    LX=0 : PRINT "{REVERSE ON}{LIGHTBLUE}":PRINT CR$:PRINT "{REVERSE OFF}{WHITE}" : GetInput()
    CRSTART=0
    RETURN
END FUNCTION

REM ** KEY TO SRS ICONS **
FUNCTION ShowKey()
    PRINT : PRINT "{13}KEY TO SHORT RANGE SCANNER ICONS:" : PRINT
    PRINT " {CYAN}E{WHITE} = THE USS ENTERPRISE"
    PRINT " {CYAN}B{WHITE} = FEDERATION STARBASE"
    PRINT " {CYAN}*{WHITE} = STAR"
    PRINT " {CYAN}K{WHITE} = KLINGON BATTLE CRUISER"
    RETURN
END FUNCTION

REM ** LIST OF COMMANDS **
FUNCTION ShowCommands()
    PRINT : PRINT "{13}USE THESE COMMANDS:" : PRINT
    PRINT " {CYAN}NAV{WHITE} - TO SET COURSE"
    PRINT " {CYAN}SRS{WHITE} - FOR SHORT RANGE SCAN"
    PRINT " {CYAN}LRS{WHITE} - FOR LONG RANGE SCAN"
    PRINT " {CYAN}SLS{WHITE} - FOR SHORT & LONG RANGE SCAN"
    PRINT " {CYAN}PHA{WHITE} - TO FIRE PHASERS"
    PRINT " {CYAN}TOR{WHITE} - TO FIRE PHOTON TORPEDOES"
    PRINT " {CYAN}SHE{WHITE} - TO RAISE OR LOWER SHIELDS"
    PRINT " {CYAN}DAM{WHITE} - FOR DAMAGE CONTROL REPORTS"
    PRINT " {CYAN}COM{WHITE} - TO CALL ON LIBRARY-COMPUTER"
    PRINT " {CYAN}KEY{WHITE} - DISPLAY KEY TO SRS ICONS"
    PRINT " {CYAN}HLP{WHITE} - THIS LIST OF COMMANDS"
    PRINT " {CYAN}XXX{WHITE} - TO RESIGN YOUR COMMAND"
    RETURN
END FUNCTION

REM ** DIRECTION HELPER **
FUNCTION ShowDirections()
    PRINT ""
    PRINT " ENTER A NUMBER       4  3  2"
    PRINT " BETWEEN 1 AND 9       . . ."
    PRINT "                        ..."
    PRINT " DECIMALS MAY BE    5 ---*--- 1"
    PRINT " USED (EG. 8.57)        ..."
    PRINT "                       . . ."
    PRINT "                      6  7  8"
    RETURN
END FUNCTION

REM ** GALAXY MAP ROMAN NUMERALS **
FUNCTION RomanNumeral()

    PRINT "";
    SELECT CASE J
    CASE 1, 5
        PRINT " I ";;
    CASE 2, 6
        PRINT "II ";
    CASE 3, 7
        PRINT "III";
    CASE 4, 8
        PRINT "IV ";
    END SELECT
    PRINT " "; : RETURN
END FUNCTION

REM ** COLOURS FOR IN-GAME **
FUNCTION InitColours()
    ACOL$="{BLACK}" : REM CHR$(144) : REM 144 = (00) BLACK
    BCOL$="{WHITE}" : REM CHR$(005) : REM 005 = (01) WHITE
    CCOL$="{RED}" : REM CHR$(028) : REM 028 = (02) RED
    DCOL$="{CYAN}" : REM CHR$(159) : REM 159 = (03) CYAN
    ECOL$="{PINK}" : REM CHR$(156) : REM 156 = (04) VIOLET
    FCOL$="{GREEN}" : REM CHR$(030) : REM 030 = (05) GREEN
    GCOL$="{BLUE}" : REM CHR$(031) : REM 031 = (06) BLUE
    HCOL$="{YELLOW}" : REM CHR$(158) : REM 158 = (07) YELLOW
    ICOL$="{ORANGE}" : REM CHR$(129) : REM 129 = (08) ORANGE
    REM ** COLOURS FOR INITIALISATION **
    REM POKE 53280,0 : POKE 53281,0 : POKE 646,5 : RETURN
    RETURN
END FUNCTION


